/** @OnlyCurrentDoc */
function AND(...preds) { return preds.every(p => p); }
function COUNTIF(cell, str) { return (cell && cell.includes(str)) ? 1 : 0 }
function IF(pred, b0, b1) { return pred ? b0 : (b1 || 0); }
function INDEX(matrix, row, column) { return matrix[row][column]; }
function MATCH(value, array) { return array.indexOf(value); }
function MAX(...nums) { return nums.length > 1 ? Math.max(...nums) : Math.max(...nums[0]); }
function MIN(...nums) { return nums.length > 1 ? Math.min(...nums) : Math.min(...nums[0]); }
function OR(...preds) { return preds.some(p => p); }
function SUM(nums) { return nums.reduce((sum, num) => sum + num); }
function VLOOKUP(value, matrix, returnColumn) {
    for (const row of matrix) {
        if (row[0] === value) {
            return row[returnColumn-1];
        }
    }
}
function RunPlayerCombatCalculation() {
    const spreadsheet = SpreadsheetApp.getActiveSpreadsheet()
    const sheet = spreadsheet.getSheetByName("Player Combat Calc");

    for (const range of spreadsheet.getNamedRanges()) {
        const name = range.getName();
        if (name === 'CLReferenceTable') {
            this[name] = range.getRange().getValues();
        } else {
            this[name] = range.getRange().getValue();
        }
    }
    const O = [];
    const P = [];
    const Q = [];
    const R = [];
    const S = [];
    const T = [];
    const U = [];
    const V = [];
    const W = [];
    const X = [];
    const Y = [];
    const Z = [];
    const AA = [];
    const AB = [];
    const AC = [];
    const AD = [];
    const AE = [];
    const AF = [];
    const AG = [];
    const AH = [];
    const AI = [];
    const AJ = [];
    const AK = [];
    const AL = [];
    const AM = [];
    const AN = [];
    const AO = [];
    const AP = [];
    const AQ = [];
    const AR = [];
    const AS = [];
    const AT = [];
    const AU = [];
    const AV = [];
    const AW = [];
    const AX = [];
    const AY = [];
    const AZ = [];
    const BA = [];
    const BB = [];
    const BC = [];
    const BD = [];
    const BE = [];
    const BF = [];
    const BG = [];
    const BH = [];
    const BI = [];
    const BJ = [];
    const BK = [];
    const BL = [];
    const BM = [];
    const BN = [];
    const BO = [];
    const BP = [];
    const BQ = [];
    const BR = [];
    const BS = [];
    const BT = [];
    const BU = [];
    const BV = [];
    const BW = [];
    const BX = [];
    const BY = [];
    const BZ = [];
    const CA = [];
    const CB = [];
    const CC = [];
    const CD = [];
    const CE = [];
    const CF = [];
    const CG = [];
    const CH = [];
    const CI = [];
    const CJ = [];
    const CK = [];
    const CL = [];
    const CM = [];
    const CN = [];
    const CO = [];
    const CP = [];
    const CQ = [];
    const CR = [];
    const CS = [];
    const CT = [];
    const CU = [];
    const CV = [];
    const CW = [];
    const CX = [];
    const CY = [];
    const CZ = [];
    const DA = [];
    const DB = [];
    const DC = [];
    const DD = [];
    const DE = [];
    const DF = [];
    const DG = [];
    const DH = [];
    const DI = [];
    const DJ = [];
    const DK = [];
    const DL = [];
    const DM = [];
    const DN = [];
    const DO = [];
    const DP = [];
    const DQ = [];
    const DR = [];
    const DS = [];
    const DT = [];
    const DU = [];
    const DV = [];
    const DW = [];
    const DX = [];
    const DY = [];
    const DZ = [];
    const EA = [];
    const EB = [];
    const EC = [];
    const ED = [];
    const EE = [];
    const EF = [];
    const EG = [];
    const EH = [];
    const EI = [];
    const EJ = [];
    const EK = [];
    const EL = [];
    const EM = [];
    const EN = [];
    const EO = [];
    const EP = [];
    const EQ = [];
    const ER = [];
    const ES = [];
    const ET = [];
    const EU = [];
    const EV = [];
    const EW = [];
    const EX = [];
    const EY = [];
    const EZ = [];
    const FA = [];
    const FB = [];
    const FC = [];
    const FD = [];
    const FE = [];
    const FF = [];
    const FG = [];
    const FH = [];
    const FI = [];
    const FJ = [];
    const FK = [];
    const FL = [];
    const FM = [];
    const FN = [];
    const FO = [];
    const FP = [];
    const FQ = [];
    const FR = [];
    const FS = [];
    const FT = [];
    const FU = [];
    const FV = [];
    const FW = [];

    for (let i = 31; i < 32; i++) {
        T[i] = 0;
        X[i] = 0.000;
        AI[i] = 0;
        AJ[i] = 0;
        AK[i] = 0;
        AL[i] = 0;
        AM[i] = 0;
        AN[i] = 0;
        AQ[i] = 0.0;
        AR[i] = 0.0;
        AS[i] = 1.5;
        AT[i] = IF(sheet.getRange("K21").getValue()=="Yes",0,sheet.getRange("AT28").getValue());
        AU[i] = IF(sheet.getRange("K22").getValue()=="Yes",0,sheet.getRange("AU28").getValue());
        AV[i] = IF(sheet.getRange("B20").getValue()=="No Racial",TotalFightLength*2,sheet.getRange("AV28").getValue());
        AW[i] = IF( sheet.getRange("G19").getValue()==0,TotalFightLength*2,sheet.getRange("AW28").getValue());
        AX[i] = 0;
        AY[i] = 0;
        AZ[i] = 3;
        BB[i] = 0;
        BC[i] = 0;
        BD[i] = sheet.getRange("BD28").getValue();
        BE[i] = sheet.getRange("BE28").getValue();
        BF[i] = IF(COUNTIF(spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$I$21').getValue(),"*Rune")==1, sheet.getRange("BF28").getValue(),TotalFightLength);
        BG[i] = sheet.getRange("BG28").getValue();
        BH[i] = 0;
        BI[i] = sheet.getRange("BI28").getValue();
        BJ[i] = sheet.getRange("R2").getValue();
        BL[i] = (110+sheet.getRange("Z19").getValue())*MasterMarksmanAP*SurvInstinctsAP;
        BN[i] = sheet.getRange("R1").getValue();
        BR[i] = 0;
        BS[i] = sheet.getRange("R11").getValue();
        BT[i] = sheet.getRange("R10").getValue();
        BU[i] = 1;
        BV[i] = BS[i]*BU[i]*(1+BT[i]/HasteRatingRatio/100);
        BW[i] = sheet.getRange("R4").getValue();
        CB[i] = RangedWeaponSpeed/BV[i];
        CC[i] = 0.5/BV[i];
        CF[i] = 1.5/BV[i];
        CL[i] = sheet.getRange("R14").getValue()+spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$31').getValue();
        CN[i] = (sheet.getRange("R12").getValue()+sheet.getRange("CN29").getValue())*(1-sheet.getRange("R13").getValue());
        CQ[i] = sheet.getRange("R14").getValue();
        CR[i] = sheet.getRange("R12").getValue();
        CS[i] = sheet.getRange("CS29").getValue()/BU[i];
        CW[i] = "Coeffs";
        CX[i] = 1.20;
        CY[i] = 1.40;
        CZ[i] = 0;
        DA[i] = 0;
        DB[i] = 1.3;
        DC[i] = 1.25;
        DD[i] = 1.5;
        DE[i] = 2.8;
        DF[i] = 0;
        DG[i] = 0;
        DH[i] = sheet.getRange("DH29").getValue();
        DI[i] = IF(DH[i]>1,1,0);
        DR[i] = 0;
        DS[i] = 0;
        DT[i] = 0;
        DU[i] = 0;
        DV[i] = 0;
        DW[i] = 0;
        DX[i] = 0;
        DY[i] = 0;
        DZ[i] = 0;
        EA[i] = 0;
        EB[i] = 0;
        EC[i] = 0;
        ED[i] = 0;
        EE[i] = 0;
        EF[i] = 0;
        EG[i] = 0;
        EH[i] = 0.0;
        EI[i] = 0.0;
        EK[i] = 0;
        EL[i] = 0;
        EM[i] = 0;
        EN[i] = 0;
        EO[i] = 0;
        EQ[i] = 0;
        ER[i] = 0;
        ES[i] = 0;
        ET[i] = 0;
        EU[i] = 0.00;
        EV[i] = 0.00;
        EW[i] = 0.00;
        EX[i] = 0.00;
        EY[i] = 0.00;
        EZ[i] = 0.00;
        FA[i] = 0.00;
        FB[i] = 0.00;
        FG[i] = 0;
        FH[i] = 0;
        FI[i] = 0;
        FJ[i] = 0;
        FK[i] = 0;
        FL[i] = 0;
        FM[i] = 0;
        FN[i] = 0;
        FO[i] = 0;
        FP[i] = 0;
        FQ[i] = 0;
        FR[i] = 0;
        FS[i] = 0.00;
        FT[i] = 0.00;
        FU[i] = 0.00;
        FV[i] = IF(sheet.getRange("FV28").getValue()==0,0,0);
        FW[i] = 0;
        AP[i] = IF(DV[i]==1,3,IF(DW[i]==1,6,IF(DX[i]==1,5,IF(DY[i]==1,7,IF(DZ[i]==1,11,IF(EG[i]==1,12,20))))));
        BA[i] = IF(spreadsheet.getSheetByName('Talents').getRange('E71').getValue()==1,BI[i],TotalFightLength*2);
        BP[i] = (IF(FQ[i]>0,110,0)+sheet.getRange("Z19").getValue())*SurvInstinctsAP;
        O[i] = IF(AND(EK[i]==18,AP[i]==20),18, MIN(IF(AW[i]<=0,1,20),IF(AV[i]<=0,2,20),IF(sheet.getRange("K21").getValue()=="Yes",AP[i], IF(AT[i]<=0,3,20)),IF(sheet.getRange("K22").getValue()=="Yes",AP[i], IF(AU[i]<=0,6,20)),IF(BI[i]<=0,4,20), IF(CW[i]=="Auto",18,IF(CW[i]=="Steady",19,IF(CW[i]=="Multi-Shot",14,IF(CW[i]=="Raptor",13,IF(CW[i]=="Melee",15,IF(CW[i]=="Arcane Shot",17,20)))))),AP[i],IF(BD[i]<=0,8,20),IF(BE[i]<=0,9,20),IF(BF[i]<=0,11.5,20),IF(BA[i]<=0,11.6,20),IF(BG[i]<=0,10,20)));
        Q[i] = VLOOKUP(O[i],CLReferenceTable,2,false);
        S[i] = IF(O[i]==20,0,Math.floor(VLOOKUP(O[i],CLReferenceTable,5,false)*IF(sheet.getRange("AD30").getValue()>0,0.8,1),0));
        U[i] = MIN(FinalMana-S[i]+T[i],FinalMana);
        Y[i] = X[i]+IF(Q[i]=="Auto",CC[i],IF(Q[i]=="Steady",CF[i]));
        Z[i] = IF(VLOOKUP(O[i],CLReferenceTable,14,false)=="YES",X[i]+1.5,0);
        AA[i] = IF(OR(Q[i]=="Blood Fury", Q[i]=="Berserking"),VLOOKUP(O[i],CLReferenceTable,7,false),0);
        AB[i] = MAX(0,IF(Q[i]==sheet.getRange("B21").getValue(),sheet.getRange("G21").getValue(),0));
        AC[i] = MAX(0,IF(Q[i]==sheet.getRange("B22").getValue(),sheet.getRange("G22").getValue(),0));
        AD[i] = IF(Q[i]=="The Beast Within",18,0);
        AE[i] = IF(Q[i]=="Quick Shots",12,0);
        AF[i] = IF(Q[i]=="Blood Lust",40,0);
        AG[i] = IF(Q[i]=="Haste Potion",15,0);
        AH[i] = IF(Q[i]=="Drums",sheet.getRange("G26").getValue(),0);
        AO[i] = IF(Q[i]=="Rapid",sheet.getRange("G8").getValue(),0);
        BK[i] = (IF(AA[i]>0,sheet.getRange("H20").getValue(),0)+IF(AB[i]>0,sheet.getRange("H21").getValue(),0)+IF(AC[i]>0,sheet.getRange("H22").getValue(),0))*MasterMarksmanAP*SurvInstinctsAP;
        BM[i] = BK[i]+BJ[i]+BL[i];
        BO[i] = BK[i]*SurvInstinctsAP/MasterMarksmanAP;
        BQ[i] = BN[i]+BO[i]+BP[i];
        BZ[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1));
        CG[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1));
        CI[i] = BZ[i]*BarrageMod*PvPGloveMod;
        CO[i] = sheet.getRange("R15").getValue()*(IF(AD[i]>0,1.1,1));
        CT[i] = CO[i];
        EJ[i] = IF(O[i]==8,1,0);
        FC[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),0,IF(Y[i]>=sheet.getRange("C31").getValue(),1,0));
        FD[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),1,0);
        FE[i] = IF(Y[i]>=sheet.getRange("C33").getValue(),1,0);
        FF[i] = IF(Y[i]>=sheet.getRange("C34").getValue(),1,0);
        P[i] = IF(Q[i]=="Auto", 1, IF(Q[i]=="Steady", 2,IF(Q[i]=="Multi-Shot", 3,IF(Q[i]=="Raptor", 4, IF(Q[i]=="Melee", 5,IF(Q[i]=="Arcane Shot", 6, 0))))));
        V[i] = MAX((sheet.getRange("V2").getValue()-spreadsheet.getSheetByName('Gear').getRange('$Z$24').getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0)-IF(FG[i]>0,sheet.getRange("E39").getValue(),0))-IF(FJ[i]>0,FJ[i]*200,0)-IF(ER[i]==1,300,0)- IF(AL[i]>0, sheet.getRange("V28").getValue(),0),0);
        W[i] = V[i]/(V[i]+400 + 85 * ((5.5 * 70) - 265.5));
        BX[i] = MAX(0,sheet.getRange("R7").getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0));
        BY[i] = sheet.getRange("R6").getValue()*(1-BX[i]);
        CA[i] = (BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*(1-BY[i]-BX[i])+(BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*BY[i]*RangeCritDamage;
        CE[i] = BY[i]+sheet.getRange("CE29").getValue()*(1-sheet.getRange("R7").getValue());
        CH[i] = (spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*(1-BY[i]-BX[i])+(spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*BY[i]*RangeCritDamage;
        CJ[i] = BY[i]+sheet.getRange("CJ29").getValue()*(1-sheet.getRange("R7").getValue());
        CK[i] = (sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*(1-CJ[i]-BX[i])+(sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*CJ[i]*RangeCritDamage;
        CM[i] = MAX(0,spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$7').getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0))+spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$8').getValue();
        CP[i] = (CL[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CN[i])*CO[i]+(CL[i]+BQ[i]*MainhandSpeed/14)*CN[i]*MeleeCritDamage*CO[i];
        CU[i] = (CQ[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*0.25*CT[i]*0.76;
        CV[i] = (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*0.25*CT[i]*0.76;
        DJ[i] = IF(P[i]==1,1,0);
        DK[i] = IF(P[i]==2,1,0);
        DL[i] = IF(P[i]==3,1,0);
        DM[i] = IF(P[i]==6,1,0);
        DN[i] = IF(P[i]==4,1,0);
        DO[i] = IF(P[i]==5,1,0);
        DP[i] = IF(P[i]==7,1,0);
        DQ[i] = SUM([DJ[i], DK[i], DL[i], DM[i], DN[i], DO[i], DP[i]]);
        CD[i] = (sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*(1-CE[i]-BX[i])+(sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*CE[i]*RangeCritDamage;
        R[i] = IF(Q[i]=="Arcane Shot",CH[i], IF(O[i]==20,0, IF(Q[i]=="Auto",CA[i],IF(Q[i]=="Steady",CD[i],IF(Q[i]=="Multi-Shot",CK[i],IF(Q[i]=="Raptor",CP[i],IF(Q[i]=="Melee",CU[i],IF(Q[i]=="Windfury Attack",CV[i],0)))))))*(1-W[i]))+IF(Q[i]=="Romulo's Poison Vial",spreadsheet.getSheetByName('Items Calc').getRange('$B$36').getValue()*BZ[i]);
    console.log(O[i],P[i],Q[i],R[i],S[i],T[i],U[i],V[i],W[i],X[i],Y[i],Z[i],AA[i],AB[i],AC[i],AD[i],AE[i],AF[i],AG[i],AH[i],AI[i],AJ[i],AK[i],AL[i],AM[i],AN[i],AO[i],AP[i],AQ[i],AR[i],AS[i],AT[i],AU[i],AV[i],AW[i],AX[i],AY[i],AZ[i],BA[i],BB[i],BC[i],BD[i],BE[i],BF[i],BG[i],BH[i],BI[i],BJ[i],BK[i],BL[i],BM[i],BN[i],BO[i],BP[i],BQ[i],BR[i],BS[i],BT[i],BU[i],BV[i],BW[i],BX[i],BY[i],BZ[i],CA[i],CB[i],CC[i],CD[i],CE[i],CF[i],CG[i],CH[i],CI[i],CJ[i],CK[i],CL[i],CM[i],CN[i],CO[i],CP[i],CQ[i],CR[i],CS[i],CT[i],CU[i],CV[i],CW[i],CX[i],CY[i],CZ[i],DA[i],DB[i],DC[i],DD[i],DE[i],DF[i],DG[i],DH[i],DI[i],DJ[i],DK[i],DL[i],DM[i],DN[i],DO[i],DP[i],DQ[i],DR[i],DS[i],DT[i],DU[i],DV[i],DW[i],DX[i],DY[i],DZ[i],EA[i],EB[i],EC[i],ED[i],EE[i],EF[i],EG[i],EH[i],EI[i],EJ[i],EK[i],EL[i],EM[i],EN[i],EO[i],EP[i],EQ[i],ER[i],ES[i],ET[i],EU[i],EV[i],EW[i],EX[i],EY[i],EZ[i],FA[i],FB[i],FC[i],FD[i],FE[i],FF[i],FG[i],FH[i],FI[i],FJ[i],FK[i],FL[i],FM[i],FN[i],FO[i],FP[i],FQ[i],FR[i],FS[i],FT[i],FU[i],FV[i],FW[i],);
    }
    for (let i = 32; i < 33; i++) {
        X[i] = Y[i-1];
        AQ[i] = IF(Q[i-1]=="Auto",CB[i-1]-CC[i-1],AQ[i-1]-Y[i-1]);
        AR[i] = Z[i-1]-Y[i-1]+AR[i-1];
        AS[i] = IF(Q[i-1]=="Multi-Shot",sheet.getRange("F7").getValue(),AS[i-1]);
        AT[i] = IF(Q[i-1]==sheet.getRange("B22").getValue(),IF(AT[i-1]>sheet.getRange("O21").getValue(),AT[i-1]-Y[i-1],sheet.getRange("O21").getValue()), IF(Q[i-1]==sheet.getRange("B21").getValue(),sheet.getRange("F21").getValue(),AT[i-1]-(Y[i-1])));
        AU[i] = IF(Q[i-1]==sheet.getRange("B21").getValue(),IF(AU[i-1]>sheet.getRange("O22").getValue(),AU[i-1]-Y[i-1],sheet.getRange("O22").getValue()),IF(Q[i-1]==sheet.getRange("B22").getValue(),sheet.getRange("F22").getValue(),AU[i-1]-Y[i-1]));
        AV[i] = IF(OR(Q[i-1]=="Blood Fury", Q[i-1]=="Berserking"),VLOOKUP(O[i-1],CLReferenceTable,6,false),AV[i-1]-(Y[i-1]));
        AW[i] = IF(Q[i-1]=="The Beast Within",sheet.getRange("F19").getValue(),AW[i-1]-(Y[i-1]));
        AX[i] = IF(Q[i-1]=="Raptor",6,AX[i-1]-(Y[i-1]));
        AY[i] = IF(Q[i-1]=="Melee",CS[i-1],AY[i-1]-(Y[i-1]));
        AZ[i] = IF(Q[i-1]=="Arcane Shot",sheet.getRange("F6").getValue(),AZ[i-1]);
        BA[i] = IF(Q[i-1]=="Readiness",VLOOKUP(O[i-1],CLReferenceTable,6,false),BA[i-1]-(Y[i-1]));
        BB[i] = IF(Q[i-1]=="Band of the Eternal Champion",60,BB[i-1]-(Y[i-1]));
        BC[i] = IF(Q[i-1]=="Quick Shots",CB[i-1],BC[i-1]-(Y[i-1]));
        BD[i] = IF(Q[i-1]=="Blood Lust",IF(AND(sheet.getRange("BE19").getValue()!=0,EJ[i-1]==1),sheet.getRange("BE19").getValue(),sheet.getRange("BE18").getValue()),BD[i-1]-(Y[i-1]));
        BE[i] = IF(O[i-1]==9,120,BE[i-1]-(Y[i-1]));
        BF[i] = IF(O[i-1]==11.5,120,BF[i-1]-(Y[i-1]));
        BG[i] = IF(Q[i-1]=="Drums",sheet.getRange("F26").getValue(),BG[i-1]-(Y[i-1]));
        BH[i] = IF(O[i-1]==12,5,BH[i-1]-(Y[i-1]));
        BI[i] = IF(Q[i-1]=="Rapid",VLOOKUP(O[i-1],CLReferenceTable,6,false),BI[i-1]-(Y[i-1]));
        BJ[i] = sheet.getRange("R2").getValue();
        BN[i] = sheet.getRange("R1").getValue();
        BS[i] = sheet.getRange("R11").getValue();
        BT[i] = sheet.getRange("R10").getValue()+IF(AC[i-1]>0,sheet.getRange("J22").getValue(),0)+IF(AB[i-1]>0,sheet.getRange("J21").getValue(),0)+IF(AG[i-1]>0,sheet.getRange("J25").getValue(),0)+IF(AH[i-1]>0,sheet.getRange("J26").getValue(),0);
        BU[i] = IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*IF(AF[i-1]>0,1.3,1)*IF(AA[i-1]>0,1+sheet.getRange("I20").getValue(),1);
        BV[i] = BS[i]*BU[i]*(1+BT[i]/HasteRatingRatio/100);
        BW[i] = sheet.getRange("R4").getValue();
        CB[i] = RangedWeaponSpeed/BV[i];
        CC[i] = 0.5/BV[i];
        CF[i] = 1.5/BV[i];
        CL[i] = sheet.getRange("CL31").getValue();
        CQ[i] = sheet.getRange("CQ31").getValue();
        CS[i] = sheet.getRange("CS29").getValue()/BV[i]*IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*BS[i];
        CW[i] = "Auto";
        CX[i] = CD[i-1]/((MAX(AR[i],0)*(CB[i-1]*sheet.getRange("CX31").getValue())+CF[i-1]));
        CY[i] = CA[i-1]/(MAX(AQ[i],0)*CB[i-1]*sheet.getRange("CY31").getValue()+CC[i-1]);
        DB[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$11').getValue()==true, CP[i-1]/(MAX(AX[i],0)+sheet.getRange("D9").getValue())/(CB[i-1]*sheet.getRange("DB31").getValue()),0);
        DC[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$12').getValue()==true, CU[i-1]/(MAX(AY[i],0)+sheet.getRange("D11").getValue())/(CB[i-1]*sheet.getRange("DC31").getValue()),0);
        DD[i] = 20.0;
        DE[i] = 200.0;
        DF[i] = 0;
        DG[i] = MAX(Z[i-1]-Y[i-1],0);
        DR[i] = IF(P[i-1]>0,1,0)+DR[i-1];
        DS[i] = DR[i];
        DT[i] = IF(sheet.getRange("Z6").getValue()==2,DQ[i-1],IF(sheet.getRange("Z6").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z6").getValue()==3,DK[i-1],0)));
        DU[i] = IF(sheet.getRange("Z7").getValue()==2,DQ[i-1],IF(sheet.getRange("Z7").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z7").getValue()==3,DK[i-1],0)));
        DV[i] = MAX(0,IF(AT[i]>0,0,MIN(DT[i]*sheet.getRange("Z4").getValue()+DV[i-1],1)-IF(Q[i-1]==EquippedTrinket1,1,0)));
        DW[i] = MAX(0,IF(AU[i]>0,0,MIN(DU[i]*sheet.getRange("Z5").getValue()+DW[i-1],1)-IF(Q[i-1]==EquippedTrinket2,1,0)));
        DX[i] = MIN(DJ[i-1]*sheet.getRange("Z3").getValue()+DX[i-1],1)-IF(Q[i-1]=="Quick Shots",1,0);
        DY[i] = MIN(DQ[i-1]*sheet.getRange("Z8").getValue()+DY[i-1],1)-IF(Q[i-1]=="Master Tactician",1,0);
        EA[i] = IF(OR(EquippedRing1=="Band of the Eternal Champion", EquippedRing2=="Band of the Eternal Champion"), IF(BB[i]>0,0,MIN(DQ[i-1]*sheet.getRange("Z13").getValue()+EA[i-1],1)-IF(Q[i-1]=="Band of the Eternal Champion",1,0)),0);
        EB[i] = IF(EquippedRanged!="Don Santos' Famous Hunting Rifle",0,MIN((DJ[i-1]+DK[i-1]+DL[i-1]+DM[i-1])*sheet.getRange("Z14").getValue()+EB[i-1],1)-IF(Q[i-1]=="Santos' Blessing",1,0));
        EC[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z15").getValue()+EC[i-1],1)-IF(Q[i-1]==EnchantMainhand,1,0);
        ED[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z16").getValue()+ED[i-1],1)-IF(Q[i-1]=="Windfury Attack",1,0);
        EE[i] = MIN(DK[i-1]*sheet.getRange("Z12").getValue()+EE[i-1],1)-IF(EE[i-1]==1,1,0);
        EH[i] = 0.0;
        EK[i] = 0;
        ET[i] = 0;
        CZ[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$9').getValue()==true, CK[i-1]/(MAX(AS[i],0)+CC[i-1])/(DD[i]),0);
        DA[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$10').getValue()==true, (CH[i-1]*(1+W[i-1]))/(MAX(AZ[i],0)+0.01)/(DE[i]),0);
        DH[i] = IF(DQ[i-1]==0,DH[i-1], IF(DS[i]>DS[i-1],sheet.getRange("DH29").getValue(),0)+DH[i-1]-DI[i-1]);
        DI[i] = IF(DH[i]>1,1,0);
        DZ[i] = MIN(DI[i]*sheet.getRange("Z9").getValue()+DZ[i-1],1)-IF(Q[i-1]=="Expose Weakness",1,0);
        EG[i] = IF(sheet.getRange("EG28").getValue()==true, IF(BH[i]<=0,IF(EH[i]>0,1,0),0),0);
        AP[i] = IF(DV[i]==1,3,IF(DW[i]==1,6,IF(DX[i]==1,5,IF(DY[i]==1,7,IF(DZ[i]==1,11,IF(AND(EG[i]==1,75<=U[i-1]),12,IF(EA[i]==1,11.2,IF(EB[i]==1,11.1,IF(EC[i]==1,11.3,IF(ED[i]==1,11.4,20))))))))));
        O[i] = IF(AND(EK[i]==18,AP[i]==20),18, MIN(IF(AW[i]<=0,1,20),IF(AV[i]<=0,2,20),IF(sheet.getRange("K21").getValue()=="Yes",AP[i], IF(AT[i]<=0,3,20)),IF(sheet.getRange("K22").getValue()=="Yes",AP[i], IF(AU[i]<=0,6,20)),IF(BI[i]<=0,4,20), IF(CW[i]=="Auto",18,IF(CW[i]=="Steady",19,IF(CW[i]=="Multi-Shot",14,IF(CW[i]=="Raptor",13,IF(CW[i]=="Melee",15,IF(CW[i]=="Arcane Shot",17,20)))))),AP[i],IF(BD[i]<=0,8,20),IF(BE[i]<=0,9,20),IF(BF[i]<=0,11.5,20),IF(BA[i]<=0,11.6,20),IF(BG[i]<=0,10,20)));
        Q[i] = VLOOKUP(O[i],CLReferenceTable,2,false);
        S[i] = IF(O[i]==20,0,Math.floor(VLOOKUP(O[i],CLReferenceTable,5,false)*IF(AD[i-1]>0,0.8,1),0));
        Y[i] = X[i]+IF(Q[i]=="Auto",CC[i], IF(Q[i]=="Steady",CF[i],IF(Q[i]=="Multi-Shot",CC[i],IF(Q[i]=="Raptor",sheet.getRange("D9").getValue(),IF(Q[i]=="Melee",sheet.getRange("D11").getValue(),IF(Q[i]=="Arcane Shot", sheet.getRange("D6").getValue(), IF(Q[i]=="None",MIN(MAX(AQ[i],0),MAX(AR[i],0),MAX(AS[i],0),0),0)))))));
        Z[i] = IF(VLOOKUP(O[i],CLReferenceTable,14,false)=="YES",X[i]+1.5,IF(X[i]<Z[i-1],Z[i-1],0));
        AA[i] = MAX(0,IF(OR(Q[i]=="Blood Fury", Q[i]=="Berserking"),VLOOKUP(O[i],CLReferenceTable,7,false),AA[i-1]-(Y[i]-Y[i-1])));
        AB[i] = MAX(0,IF(Q[i]==sheet.getRange("B21").getValue(),sheet.getRange("G21").getValue(),AB[i-1]-(Y[i]-Y[i-1])));
        AC[i] = MAX(0,IF(Q[i]==sheet.getRange("B22").getValue(),sheet.getRange("G22").getValue(),AC[i-1]-(Y[i]-Y[i-1])));
        AD[i] = MAX(0,IF(Q[i]=="The Beast Within",18,AD[i-1]-(Y[i]-Y[i-1])));
        AE[i] = MAX(0,IF(Q[i]=="Quick Shots",12,AE[i-1]-(Y[i]-Y[i-1])));
        AF[i] = MAX(0,IF(Q[i]=="Blood Lust",40,AF[i-1]-(Y[i]-Y[i-1])));
        AG[i] = MAX(0,IF(Q[i]=="Haste Potion",15,IF(Q[i]=="Fel Mana Potion",24,AG[i-1]-(Y[i]-Y[i-1]))));
        AH[i] = MAX(0,IF(Q[i]=="Drums",sheet.getRange("G26").getValue(),AH[i-1]-(Y[i]-Y[i-1])));
        AI[i] = MAX(0,IF(Q[i]=="Master Tactician",8,AI[i-1]-(Y[i]-Y[i-1])));
        AJ[i] = MAX(0,IF(Q[i]=="Band of the Eternal Champion",10,AJ[i-1]-(Y[i]-Y[i-1])));
        AK[i] = MAX(0,IF(Q[i]=="Santos' Blessing",10,AK[i-1]-(Y[i]-Y[i-1])));
        AL[i] = MAX(0,IF(Q[i]==EnchantMainhand,15,AL[i-1]-(Y[i]-Y[i-1])));
        AM[i] = MAX(0,IF(Q[i]=="Expose Weakness",7,AM[i-1]-(Y[i]-Y[i-1])));
        AN[i] = IF(SetBeastLord>=4,IF(MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1])))>0,MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1]))),0),0);
        AO[i] = MAX(0,IF(Q[i]=="Rapid",sheet.getRange("G8").getValue(),AO[i-1]-(Y[i]-Y[i-1])));
        BZ[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CG[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FN[i-1]>0,sheet.getRange("I41").getValue(),1)*IF(FO[i-1]>0,sheet.getRange("I42").getValue(),1);
        CI[i] = BZ[i]*BarrageMod*PvPGloveMod;
        CO[i] = sheet.getRange("R15").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CT[i] = CO[i];
        EF[i] = IF(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),DT[i]*sheet.getRange("Z4").getValue()+EF[i-1],IF(AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0),DU[i]*sheet.getRange("Z5").getValue()+EF[i-1],0))-IF(ET[i-1]==1,1,0);
        EI[i] = IF(EquippedTrinket1=="Blackened Naaru Sliver", MIN(IF(AB[i]>0,44*DT[i]+EI[i-1],0),440),0)+IF(EquippedTrinket2=="Blackened Naaru Sliver", MIN(IF(AC[i]>0,44*DU[i]+EI[i-1],0),440),0);
        EJ[i] = IF(O[i]==8,1+EJ[i-1],EJ[i-1]);
        EL[i] = IF(sheet.getRange("B25").getValue()=="Super Mana Potion",IF(O[i]==9,spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$K$20').getValue(),0),0);
        EM[i] = IF((IF(sheet.getRange("B25").getValue()=="Fel Mana Potion",Math.ceil(AG[i]/3)-Math.ceil(AG[i-1]/3),0)+EM[i-1])!=EM[i-1],IF(O[i]==9,0,1),0);
        EN[i] = IF(AND(O[i]==11.5,COUNTIF(spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$I$21').getValue(),"*Rune")==1),1200,0);
        EO[i] = IF(Y[i]-Y[i-1]==0,0,IF(AQ[i]<0,Math.abs(AQ[i]),0));
        ER[i] = IF(OR(AND(EquippedTrinket1=="Madness of the Betrayer",AB[i]>0),AND(EquippedTrinket2=="Madness of the Betrayer",AC[i]>0)),1,0);
        EU[i] = IF(AB[i]>0,Y[i]-Y[i-1],0)+IF(AB[i]==0,AB[i-1],0);
        EV[i] = IF(AC[i]>0,Y[i]-Y[i-1],0)+IF(AC[i]==0,AC[i-1],0);
        EW[i] = IF(AE[i]>0,Y[i]-Y[i-1],0)+IF(AE[i]==0,AE[i-1],0);
        EX[i] = IF(AI[i]>0,Y[i]-Y[i-1],0)+IF(AI[i]==0,AI[i-1],0);
        EY[i] = IF(AM[i]>0,Y[i]-Y[i-1],0)+IF(AM[i]==0,AM[i-1],0);
        EZ[i] = IF(AJ[i]>0,Y[i]-Y[i-1],0)+IF(AJ[i]==0,AJ[i-1],0);
        FA[i] = IF(AK[i]>0,Y[i]-Y[i-1],0)+IF(AK[i]==0,AK[i-1],0);
        FB[i] = IF(AL[i]>0,Y[i]-Y[i-1],0)+IF(AL[i]==0,AL[i-1],0);
        FC[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),0,IF(Y[i]>=sheet.getRange("C31").getValue(),1,0));
        FD[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),1,0);
        FE[i] = IF(Y[i]>=sheet.getRange("C33").getValue(),1,0);
        FF[i] = IF(Y[i]>=sheet.getRange("C34").getValue(),1,0);
        FG[i] = IF(AN[i]>0,1,0);
        FH[i] = IF(Y[i]>sheet.getRange("C35").getValue(),1,0);
        FI[i] = IF(Y[i]>sheet.getRange("C36").getValue(),1,0);
        FJ[i] = IF(OR(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0)),MIN(6,IF(ET[i]==1,ET[i]+FJ[i-1],FJ[i-1])),0);
        FK[i] = IF(Y[i]>sheet.getRange("C38").getValue(),1,0);
        FL[i] = IF(Y[i]>sheet.getRange("C37").getValue(),1,0);
        FM[i] = IF(Y[i]>sheet.getRange("C40").getValue(),1,0);
        FN[i] = IF(Y[i]>sheet.getRange("C41").getValue(),1,0);
        FO[i] = IF(Y[i]>sheet.getRange("C42").getValue(),1,0);
        FP[i] = IF(Y[i]>sheet.getRange("C43").getValue(),1,0);
        FQ[i] = IF(Y[i]>sheet.getRange("C44").getValue(),1,0);
        FS[i] = IF(AF[i]>0,Y[i]-Y[i-1],0)+IF(AF[i]==0,AF[i-1],0);
        FT[i] = MAX(sheet.getRange("V2").getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0),0)*(Y[i]-Y[i-1])/ActiveFightDuration;
        FU[i] = IF(AD[i]>0,Y[i]-Y[i-1],0)+IF(AD[i]==0,AD[i-1],0);
        FV[i] = IF(sheet.getRange("FV28").getValue()==0, IF(FV[i-1]-(X[i]-Y[i])>10,FV[i-1]-(X[i]-Y[i])-10,FV[i-1]-(X[i]-Y[i])),0);
        P[i] = IF(Q[i]=="Auto", 1, IF(Q[i]=="Steady", 2,IF(Q[i]=="Multi-Shot", 3,IF(Q[i]=="Raptor", 4, IF(Q[i]=="Melee", 5,IF(Q[i]=="Arcane Shot", 6,IF(Q[i]=="Windfury Attack", 7, 0)))))));
        T[i] = IF(OR(P[i]>0,O[i]==12),IF(FM[i]==1,sheet.getRange("V12").getValue(),0)+IF(AND(EquippedRanged=="Black Bow of the Betrayer",P[i]!=4,P[i]!=5),8,0),0) +IF(Y[i]>5*Math.ceil(Y[i-1]/5),sheet.getRange("V19").getValue(),0) +IF(OR(P[i]==2,P[i]==3),S[i]*IF(EE[i]==1,0.4,0),0)+IF(O[i]==9,EL[i],0)+IF(EM[i]>0,400,0)+IF(O[i]==11.5,EN[i],0);
        U[i] = MIN(U[i-1]-S[i]+T[i],FinalMana);
        V[i] = MAX((sheet.getRange("V2").getValue()-spreadsheet.getSheetByName('Gear').getRange('$Z$24').getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0)-IF(FG[i]>0,sheet.getRange("E39").getValue(),0))-IF(FJ[i]>0,FJ[i]*200,0)-IF(ER[i]==1,300,0)- IF(AL[i]>0, sheet.getRange("V28").getValue(),0),0);
        W[i] = V[i]/(V[i]+400 + 85 * ((5.5 * 70) - 265.5));
        BP[i] = (IF(FQ[i]>0,110,0) + IF(AM[i]>0,sheet.getRange("H29").getValue(),IF(FP[i]>0,sheet.getRange("H43").getValue(),0)) + sheet.getRange("Z19").getValue())*SurvInstinctsAP;
        BR[i] = (IF(AL[i]>0,COUNTIF(sheet.getRange("B15").getValue(),"*Mongoose*")*sheet.getRange("H15").getValue(),0)+IF(AND(AB[i]>0,EquippedTrinket1=="Badge of Tenacity"),150,0)+IF(AND(AC[i]>0,EquippedTrinket2=="Badge of Tenacity"),150,0)+IF(FV[i]<=8.5,GraceofAirAgi,0))*KingsMod*(1+spreadsheet.getSheetByName('Talents').getRange('$E$66').getValue()*0.03);
        BX[i] = MAX(0,sheet.getRange("R7").getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0));
        BY[i] = (sheet.getRange("R6").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-BX[i-1]);
        CE[i] = BY[i]+sheet.getRange("CE29").getValue()*(1-BX[i-1]);
        CJ[i] = BY[i]+sheet.getRange("CJ29").getValue()*(1-BX[i-1]);
        CM[i] = MAX(0,spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$7').getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0))+spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$8').getValue();
        CN[i] = (sheet.getRange("R12").getValue()+sheet.getRange("CN29").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-CM[i-1]);
        CR[i] = sheet.getRange("R12").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100;
        DJ[i] = IF(P[i]==1,1,0);
        DK[i] = IF(P[i]==2,1,0);
        DL[i] = IF(P[i]==3,1,0);
        DM[i] = IF(P[i]==6,1,0);
        DN[i] = IF(P[i]==4,1,0);
        DO[i] = IF(P[i]==5,1,0);
        DP[i] = IF(P[i]==7,1,0);
        DQ[i] = SUM([DJ[i], DK[i], DL[i], DM[i], DN[i], DO[i], DP[i]]);
        EQ[i] = IF(EquippedTrinket1=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0)+IF(EquippedTrinket2=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0);
        ES[i] = MIN(IF(OR(P[i]==1,P[i]==2),33*spreadsheet.getSheetByName('Settings for DPS').getRange('$E$19').getValue(),0)+ES[i-1],330);
        FW[i] = BR[i]*(Y[i]-Y[i-1])/ActiveFightDuration;
        BK[i] = (IF(AA[i]>0,sheet.getRange("H20").getValue(),0)+IF(AB[i]>0,sheet.getRange("H21").getValue(),0)+IF(AC[i]>0,sheet.getRange("H22").getValue(),0)+EI[i]+EQ[i]+IF(AH[i]>0,sheet.getRange("H26").getValue(),0) +IF(AJ[i]>0,sheet.getRange("H14").getValue(),0)+ IF(AK[i]>0,sheet.getRange("H13").getValue(),0)+sheet.getRange("BR32").getValue())*MasterMarksmanAP*SurvInstinctsAP;
        BL[i] = (110+sheet.getRange("Z19").getValue()+ES[i]+IF(AM[i]>0,sheet.getRange("H29").getValue()+BR[i]/4,IF(FP[i]>0,sheet.getRange("H43").getValue(),0)))*MasterMarksmanAP*SurvInstinctsAP;
        BM[i] = BK[i]+BJ[i]+BL[i];
        BO[i] = BK[i]*sheet.getRange("Z11").getValue()/sheet.getRange("Z10").getValue();
        BQ[i] = (BN[i]+BO[i]+BP[i])*IF(FK[i-1]>0,1.1,1);
        CA[i] = (BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*(1-BY[i]-BX[i])+(BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*BY[i]*RangeCritDamage;
        CD[i] = (sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*(1-CE[i]-BX[i])+(sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*CE[i]*RangeCritDamage;
        CH[i] = (spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*(1-BY[i]-BX[i])+(spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*BY[i]*RangeCritDamage;
        CK[i] = (sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*(1-CJ[i]-BX[i])+(sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*CJ[i]*RangeCritDamage;
        CP[i] = (CL[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CN[i])*CO[i]+(CL[i]+BQ[i]*MainhandSpeed/14)*CN[i]*MeleeCritDamage*CO[i];
        CU[i] = (CQ[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*0.25*CT[i]*0.76;
        CV[i] = (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*0.25*CT[i]*0.76;
        FR[i] = (BJ[i]+BK[i])*(Y[i]-Y[i-1])/ActiveFightDuration;
        R[i] = IF(Q[i]=="Arcane Shot",CH[i], IF(O[i]==20,0, IF(Q[i]=="Auto",CA[i],IF(Q[i]=="Steady",CD[i],IF(Q[i]=="Multi-Shot",CK[i],IF(Q[i]=="Raptor",CP[i],IF(Q[i]=="Melee",CU[i],IF(Q[i]=="Windfury Attack",CV[i],0)))))))*(1-W[i]))+IF(Q[i]=="Romulo's Poison Vial",spreadsheet.getSheetByName('Items Calc').getRange('$B$36').getValue()*BZ[i]);
    console.log(O[i],P[i],Q[i],R[i],S[i],T[i],U[i],V[i],W[i],X[i],Y[i],Z[i],AA[i],AB[i],AC[i],AD[i],AE[i],AF[i],AG[i],AH[i],AI[i],AJ[i],AK[i],AL[i],AM[i],AN[i],AO[i],AP[i],AQ[i],AR[i],AS[i],AT[i],AU[i],AV[i],AW[i],AX[i],AY[i],AZ[i],BA[i],BB[i],BC[i],BD[i],BE[i],BF[i],BG[i],BH[i],BI[i],BJ[i],BK[i],BL[i],BM[i],BN[i],BO[i],BP[i],BQ[i],BR[i],BS[i],BT[i],BU[i],BV[i],BW[i],BX[i],BY[i],BZ[i],CA[i],CB[i],CC[i],CD[i],CE[i],CF[i],CG[i],CH[i],CI[i],CJ[i],CK[i],CL[i],CM[i],CN[i],CO[i],CP[i],CQ[i],CR[i],CS[i],CT[i],CU[i],CV[i],CW[i],CX[i],CY[i],CZ[i],DA[i],DB[i],DC[i],DD[i],DE[i],DF[i],DG[i],DH[i],DI[i],DJ[i],DK[i],DL[i],DM[i],DN[i],DO[i],DP[i],DQ[i],DR[i],DS[i],DT[i],DU[i],DV[i],DW[i],DX[i],DY[i],DZ[i],EA[i],EB[i],EC[i],ED[i],EE[i],EF[i],EG[i],EH[i],EI[i],EJ[i],EK[i],EL[i],EM[i],EN[i],EO[i],EP[i],EQ[i],ER[i],ES[i],ET[i],EU[i],EV[i],EW[i],EX[i],EY[i],EZ[i],FA[i],FB[i],FC[i],FD[i],FE[i],FF[i],FG[i],FH[i],FI[i],FJ[i],FK[i],FL[i],FM[i],FN[i],FO[i],FP[i],FQ[i],FR[i],FS[i],FT[i],FU[i],FV[i],FW[i],);
    }
    for (let i = 33; i < 34; i++) {
        AQ[i] = IF(Q[i-1]=="Auto",CB[i-1]-CC[i-1],AQ[i-1]-(Y[i-1]-Y[i-2]));
        AR[i] = IF(Q[i-1]=="Readiness",1,IF(Q[i-1]=="Steady",Z[i-1]-Y[i-1],MAX(AR[i-1]-(Y[i-1]-Y[i-2]),0))+IF(Q[i-1]=="Multi-Shot",Z[i-1]-Y[i-1],0)+IF(Q[i-1]=="Arcane Shot",Z[i-1]-Y[i-1],0));
        AS[i] = IF(Q[i-1]=="Readiness",1,MAX(0,IF(Q[i-1]=="Multi-Shot",sheet.getRange("F7").getValue(),IF(AS[i-1]-(Y[i-1]-Y[i-2])<AR[i],AR[i],MAX(AS[i-1]-(Y[i-1]-Y[i-2]),0)))));
        AT[i] = IF(Q[i-1]==sheet.getRange("B22").getValue(),IF(AT[i-1]>sheet.getRange("O21").getValue(),AT[i-1]-(Y[i-1]-Y[i-2]),sheet.getRange("O21").getValue()), IF(Q[i-1]==sheet.getRange("B21").getValue(),sheet.getRange("F21").getValue(),AT[i-1]-(Y[i-1]-Y[i-2])));
        AU[i] = IF(Q[i-1]==sheet.getRange("B21").getValue(),IF(AU[i-1]>sheet.getRange("O22").getValue(),AU[i-1]-(Y[i-1]-Y[i-2]),sheet.getRange("O22").getValue()),IF(Q[i-1]==sheet.getRange("B22").getValue(),sheet.getRange("F22").getValue(),AU[i-1]-(Y[i-1]-Y[i-2])));
        AV[i] = IF(OR(Q[i-1]=="Blood Fury", Q[i-1]=="Berserking"),VLOOKUP(O[i-1],CLReferenceTable,6,false),AV[i-1]-(Y[i-1]-Y[i-2]));
        AW[i] = IF(Q[i-1]=="The Beast Within",sheet.getRange("F19").getValue(),AW[i-1]-(Y[i-1]-Y[i-2]));
        AX[i] = IF(Q[i-1]=="Readiness",0,IF(Q[i-1]=="Raptor",sheet.getRange("F9").getValue(),IF(Q[i-1]=="Melee",IF(AX[i-1]<=CS[i-1],CS[i-1],AX[i-1]-(Y[i-1]-Y[i-2])),AX[i-1]-(Y[i-1]-Y[i-2]))));
        AY[i] = IF(Q[i-1]=="Melee",CS[i-1],IF(Q[i-1]=="Raptor",CS[i-1],AY[i-1]-(Y[i-1]-Y[i-2])));
        AZ[i] = IF(Q[i-1]=="Readiness",1,MAX(0,IF(Q[i-1]=="Arcane Shot",sheet.getRange("F6").getValue(),IF(AZ[i-1]-(Y[i-1]-Y[i-2])<AR[i],AR[i],MAX(AZ[i-1]-(Y[i-1]-Y[i-2]),0)))));
        BA[i] = IF(Q[i-1]=="Readiness",VLOOKUP(O[i-1],CLReferenceTable,6,false), MAX(IF( AO[i-1]>0,AO[i-1],0),BA[i-1]-(Y[i-1]-Y[i-2])));
        BB[i] = IF(Q[i-1]=="Band of the Eternal Champion",60,BB[i-1]-(Y[i-1]-Y[i-2]));
        BC[i] = MAX(0,IF(Q[i-1]=="Quick Shots",CB[i-1],BC[i-1]-(Y[i-1]-Y[i-2])));
        BD[i] = IF(Q[i-1]=="Blood Lust",IF(AND(sheet.getRange("BE19").getValue()!=0,OR(EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-1,EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-2,EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-3)),sheet.getRange("BE19").getValue(),sheet.getRange("BE18").getValue()),BD[i-1]-(Y[i-1]-Y[i-2]));
        BE[i] = IF(O[i-1]==9,120,BE[i-1]-(Y[i-1]-Y[i-2]));
        BF[i] = IF(O[i-1]==11.5,120,BF[i-1]-(Y[i-1]-Y[i-2]));
        BG[i] = IF(Q[i-1]=="Drums",sheet.getRange("F26").getValue(),BG[i-1]-(Y[i-1]-Y[i-2]));
        BH[i] = IF(Q[i-1]=="Readiness",0,IF(O[i-1]==12,5,BH[i-1]-(Y[i-1]-Y[i-2])));
        BI[i] = IF(Q[i-1]=="Readiness",0,IF(Q[i-1]=="Rapid",VLOOKUP(O[i-1],CLReferenceTable,6,false),BI[i-1]-(Y[i-1]-Y[i-2])));
        BJ[i] = sheet.getRange("R2").getValue();
        BN[i] = sheet.getRange("R1").getValue();
        BS[i] = sheet.getRange("R11").getValue();
        BT[i] = sheet.getRange("R10").getValue()+IF(AC[i-1]>0,sheet.getRange("J22").getValue(),0)+IF(AB[i-1]>0,sheet.getRange("J21").getValue(),0)+IF(AG[i-1]>0,sheet.getRange("J25").getValue(),0)+IF(AH[i-1]>0,sheet.getRange("J26").getValue(),0);
        BU[i] = IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*IF(AF[i-1]>0,1.3,1)*IF(AA[i-1]>0,1+sheet.getRange("I20").getValue(),1);
        BV[i] = BS[i]*BU[i]*(1+BT[i]/HasteRatingRatio/100);
        BW[i] = sheet.getRange("R4").getValue();
        CB[i] = RangedWeaponSpeed/BV[i];
        CC[i] = 0.5/BV[i];
        CF[i] = 1.5/BV[i];
        CL[i] = sheet.getRange("CL31").getValue();
        CQ[i] = sheet.getRange("CQ31").getValue();
        CS[i] = sheet.getRange("CS29").getValue()/BV[i]*IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*BS[i];
        CX[i] = CD[i-1]/((MAX(AR[i],0)*(CB[i-1]*sheet.getRange("CX31").getValue())+CF[i-1]));
        CY[i] = CA[i-1]/(MAX(AQ[i],0)*CB[i-1]*sheet.getRange("CY31").getValue()+CC[i-1]);
        DB[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$11').getValue()==true, CP[i-1]/(MAX(AX[i],0)+sheet.getRange("D9").getValue())/(CB[i-1]*sheet.getRange("DB31").getValue()),0);
        DC[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$12').getValue()==true, CU[i-1]/(MAX(AY[i],0)+sheet.getRange("D11").getValue())/(CB[i-1]*sheet.getRange("DC31").getValue()),0);
        DD[i] = 20.0;
        DE[i] = 200.0;
        DF[i] = 0;
        DG[i] = MAX(Z[i-1]-Y[i-1],0);
        DR[i] = IF(P[i-1]>0,1,0)+DR[i-1];
        DS[i] = DR[i];
        DT[i] = IF(sheet.getRange("Z6").getValue()==2,DQ[i-1],IF(sheet.getRange("Z6").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z6").getValue()==3,DK[i-1],0)));
        DU[i] = IF(sheet.getRange("Z7").getValue()==2,DQ[i-1],IF(sheet.getRange("Z7").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z7").getValue()==3,DK[i-1],0)));
        DV[i] = MAX(0,IF(AT[i]>0,0,MIN(DT[i]*sheet.getRange("Z4").getValue()+DV[i-1],1)-IF(Q[i-1]==EquippedTrinket1,1,0)));
        DW[i] = MAX(0,IF(AU[i]>0,0,MIN(DU[i]*sheet.getRange("Z5").getValue()+DW[i-1],1)-IF(Q[i-1]==EquippedTrinket2,1,0)));
        DX[i] = MIN(DJ[i-1]*sheet.getRange("Z3").getValue()+DX[i-1],1)-IF(Q[i-1]=="Quick Shots",1,0);
        DY[i] = MIN(DQ[i-1]*sheet.getRange("Z8").getValue()+DY[i-1],1)-IF(Q[i-1]=="Master Tactician",1,0);
        EA[i] = IF(OR(EquippedRing1=="Band of the Eternal Champion", EquippedRing2=="Band of the Eternal Champion"), IF(BB[i]>0,0,MIN(DQ[i-1]*sheet.getRange("Z13").getValue()+EA[i-1],1)-IF(Q[i-1]=="Band of the Eternal Champion",1,0)),0);
        EB[i] = IF(EquippedRanged!="Don Santos' Famous Hunting Rifle",0,MIN((DJ[i-1]+DK[i-1]+DL[i-1]+DM[i-1])*sheet.getRange("Z14").getValue()+EB[i-1],1)-IF(Q[i-1]=="Santos' Blessing",1,0));
        EC[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z15").getValue()+EC[i-1],1)-IF(Q[i-1]==EnchantMainhand,1,0);
        ED[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z16").getValue()+ED[i-1],1)-IF(Q[i-1]=="Windfury Attack",1,0);
        EE[i] = MIN(DK[i-1]*sheet.getRange("Z12").getValue()+EE[i-1],1)-IF(EE[i-1]==1,1,0);
        EH[i] = IF(DI[i-1]==1,5-(Y[i-1]-Y[i-2]), IF(EH[i-1]-(Y[i-1]-Y[i-2])>0,EH[i-1]-(Y[i-1]-Y[i-2]),0));
        EK[i] = IF(IF(O[i-1]==20,0,Math.floor(VLOOKUP(CW[i-1],sheet.getRange('$B$3:$N$29').getValues(),4,false)*IF(AD[i-2]>0,0.8,1),0))>U[i-2],18,0);
        ET[i] = 0;
        CZ[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$9').getValue()==true, CK[i-1]/(MAX(AS[i],0)+CC[i-1])/(DD[i]),0);
        DA[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$10').getValue()==true, (CH[i-1]*(1+W[i-1]))/(MAX(AZ[i],0)+0.01)/(DE[i]),0);
        DH[i] = IF(DQ[i-1]==0,DH[i-1], IF(DS[i]>DS[i-1],sheet.getRange("DH29").getValue(),0)+DH[i-1]-DI[i-1]);
        DI[i] = IF(DH[i]>1,1,0);
        DZ[i] = MIN(DI[i]*sheet.getRange("Z9").getValue()+DZ[i-1],1)-IF(Q[i-1]=="Expose Weakness",1,0);
        EG[i] = IF(sheet.getRange("EG28").getValue()==true, IF(BH[i]<=0,IF(EH[i]>0,1,0),0),0);
        AP[i] = IF(DV[i]==1,3,IF(DW[i]==1,6,IF(DX[i]==1,5,IF(DY[i]==1,7,IF(DZ[i]==1,11,IF(AND(EG[i]==1,75<=U[i-1]),12,IF(EA[i]==1,11.2,IF(EB[i]==1,11.1,IF(EC[i]==1,11.3,IF(ED[i]==1,11.4,20))))))))));
        CW[i] = IF(CX[i]+CY[i]+CZ[i]+DB[i]+DC[i]+DA[i]==0,"None",IF(S[i-1]>=U[i-1], "Auto",INDEX(sheet.getRange('$CX$30:$DC$30').getValues(),0, MATCH(MAX([CX[i], CY[i], CZ[i], DA[i], DB[i], DC[i]]),[CX[i], CY[i], CZ[i], DA[i], DB[i], DC[i]],0))));
        O[i] = IF(AND(EK[i]==18,AP[i]==20),18, MIN(IF(AW[i]<=0,1,20),IF(AV[i]<=0,2,20),IF(sheet.getRange("K21").getValue()=="Yes",AP[i], IF(AT[i]<=0,3,20)),IF(sheet.getRange("K22").getValue()=="Yes",AP[i], IF(AU[i]<=0,6,20)),IF(BI[i]<=0,4,20), IF(CW[i]=="Auto",18,IF(CW[i]=="Steady",19,IF(CW[i]=="Multi-Shot",14,IF(CW[i]=="Raptor",13,IF(CW[i]=="Melee",15,IF(CW[i]=="Arcane Shot",17,20)))))),AP[i],IF(BD[i]<=0,8,20),IF(BE[i]<=0,9,20),IF(BF[i]<=0,11.5,20),IF(BA[i]<=0,11.6,20),IF(BG[i]<=0,10,20)));
        Q[i] = VLOOKUP(O[i],CLReferenceTable,2,false);
        S[i] = IF(O[i]==20,0,Math.floor(VLOOKUP(O[i],CLReferenceTable,5,false)*IF(AD[i-1]>0,0.8,1),0));
        X[i] = Y[i-1]+IF(Q[i]=="Auto",MAX(AQ[i],0),IF(Q[i]=="Steady",MAX(AR[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Multi-Shot", MAX(AS[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Raptor",MAX(AX[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Melee",MAX(AY[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Arcane Shot",MAX(AZ[i],0)+sheet.getRange("AG22").getValue(),0))))));
        Y[i] = X[i]+IF(Q[i]=="Auto",CC[i], IF(Q[i]=="Steady",CF[i],IF(Q[i]=="Multi-Shot",CC[i],IF(Q[i]=="Raptor",sheet.getRange("D9").getValue(),IF(Q[i]=="Melee",sheet.getRange("D11").getValue(),IF(Q[i]=="Arcane Shot", sheet.getRange("D6").getValue(), IF(Q[i]=="None",MIN(MAX(AQ[i],0),MAX(AR[i],0),MAX(AS[i],0),0),0)))))));
        Z[i] = IF(VLOOKUP(O[i],CLReferenceTable,14,false)=="YES",X[i]+1.5,IF(X[i]<Z[i-1],Z[i-1],0));
        AA[i] = MAX(0,IF(OR(Q[i]=="Blood Fury", Q[i]=="Berserking"),VLOOKUP(O[i],CLReferenceTable,7,false),AA[i-1]-(Y[i]-Y[i-1])));
        AB[i] = MAX(0,IF(Q[i]==sheet.getRange("B21").getValue(),sheet.getRange("G21").getValue(),AB[i-1]-(Y[i]-Y[i-1])));
        AC[i] = MAX(0,IF(Q[i]==sheet.getRange("B22").getValue(),sheet.getRange("G22").getValue(),AC[i-1]-(Y[i]-Y[i-1])));
        AD[i] = MAX(0,IF(Q[i]=="The Beast Within",18,AD[i-1]-(Y[i]-Y[i-1])));
        AE[i] = MAX(0,IF(Q[i]=="Quick Shots",12,AE[i-1]-(Y[i]-Y[i-1])));
        AF[i] = MAX(0,IF(Q[i]=="Blood Lust",40,AF[i-1]-(Y[i]-Y[i-1])));
        AG[i] = MAX(0,IF(Q[i]=="Haste Potion",15,IF(Q[i]=="Fel Mana Potion",24,AG[i-1]-(Y[i]-Y[i-1]))));
        AH[i] = MAX(0,IF(Q[i]=="Drums",sheet.getRange("G26").getValue(),AH[i-1]-(Y[i]-Y[i-1])));
        AI[i] = MAX(0,IF(Q[i]=="Master Tactician",8,AI[i-1]-(Y[i]-Y[i-1])));
        AJ[i] = MAX(0,IF(Q[i]=="Band of the Eternal Champion",10,AJ[i-1]-(Y[i]-Y[i-1])));
        AK[i] = MAX(0,IF(Q[i]=="Santos' Blessing",10,AK[i-1]-(Y[i]-Y[i-1])));
        AL[i] = MAX(0,IF(Q[i]==EnchantMainhand,15,AL[i-1]-(Y[i]-Y[i-1])));
        AM[i] = MAX(0,IF(Q[i]=="Expose Weakness",7,AM[i-1]-(Y[i]-Y[i-1])));
        AN[i] = IF(SetBeastLord>=4,IF(MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1])))>0,MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1]))),0),0);
        AO[i] = MAX(0,IF(Q[i]=="Rapid",sheet.getRange("G8").getValue(),AO[i-1]-(Y[i]-Y[i-1])));
        BZ[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CG[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FN[i-1]>0,sheet.getRange("I41").getValue(),1)*IF(FO[i-1]>0,sheet.getRange("I42").getValue(),1);
        CI[i] = BZ[i]*BarrageMod*PvPGloveMod;
        CO[i] = sheet.getRange("R15").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CT[i] = CO[i];
        EF[i] = IF(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),DT[i]*sheet.getRange("Z4").getValue()+EF[i-1],IF(AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0),DU[i]*sheet.getRange("Z5").getValue()+EF[i-1],0))-IF(ET[i-1]==1,1,0);
        EI[i] = IF(EquippedTrinket1=="Blackened Naaru Sliver", MIN(IF(AB[i]>0,44*DT[i]+EI[i-1],0),440),0)+IF(EquippedTrinket2=="Blackened Naaru Sliver", MIN(IF(AC[i]>0,44*DU[i]+EI[i-1],0),440),0);
        EJ[i] = IF(O[i]==8,1+EJ[i-1],EJ[i-1]);
        EL[i] = IF(sheet.getRange("B25").getValue()=="Super Mana Potion",IF(O[i]==9,spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$K$20').getValue(),0),0);
        EM[i] = IF((IF(sheet.getRange("B25").getValue()=="Fel Mana Potion",Math.ceil(AG[i]/3)-Math.ceil(AG[i-1]/3),0)+EM[i-1])!=EM[i-1],IF(O[i]==9,0,1),0);
        EN[i] = IF(AND(O[i]==11.5,COUNTIF(spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$I$21').getValue(),"*Rune")==1),1200,0);
        EO[i] = IF(Y[i]-Y[i-1]==0,0,IF(AQ[i]<0,Math.abs(AQ[i]),0));
        ER[i] = IF(OR(AND(EquippedTrinket1=="Madness of the Betrayer",AB[i]>0),AND(EquippedTrinket2=="Madness of the Betrayer",AC[i]>0)),1,0);
        EU[i] = IF(AB[i]>0,Y[i]-Y[i-1],0)+IF(AB[i]==0,AB[i-1],0);
        EV[i] = IF(AC[i]>0,Y[i]-Y[i-1],0)+IF(AC[i]==0,AC[i-1],0);
        EW[i] = IF(AE[i]>0,Y[i]-Y[i-1],0)+IF(AE[i]==0,AE[i-1],0);
        EX[i] = IF(AI[i]>0,Y[i]-Y[i-1],0)+IF(AI[i]==0,AI[i-1],0);
        EY[i] = IF(AM[i]>0,Y[i]-Y[i-1],0)+IF(AM[i]==0,AM[i-1],0);
        EZ[i] = IF(AJ[i]>0,Y[i]-Y[i-1],0)+IF(AJ[i]==0,AJ[i-1],0);
        FA[i] = IF(AK[i]>0,Y[i]-Y[i-1],0)+IF(AK[i]==0,AK[i-1],0);
        FB[i] = IF(AL[i]>0,Y[i]-Y[i-1],0)+IF(AL[i]==0,AL[i-1],0);
        FC[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),0,IF(Y[i]>=sheet.getRange("C31").getValue(),1,0));
        FD[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),1,0);
        FE[i] = IF(Y[i]>=sheet.getRange("C33").getValue(),1,0);
        FF[i] = IF(Y[i]>=sheet.getRange("C34").getValue(),1,0);
        FG[i] = IF(AN[i]>0,1,0);
        FH[i] = IF(Y[i]>sheet.getRange("C35").getValue(),1,0);
        FI[i] = IF(Y[i]>sheet.getRange("C36").getValue(),1,0);
        FJ[i] = IF(OR(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0)),MIN(6,IF(ET[i]==1,ET[i]+FJ[i-1],FJ[i-1])),0);
        FK[i] = IF(Y[i]>sheet.getRange("C38").getValue(),1,0);
        FL[i] = IF(Y[i]>sheet.getRange("C37").getValue(),1,0);
        FM[i] = IF(Y[i]>sheet.getRange("C40").getValue(),1,0);
        FN[i] = IF(Y[i]>sheet.getRange("C41").getValue(),1,0);
        FO[i] = IF(Y[i]>sheet.getRange("C42").getValue(),1,0);
        FP[i] = IF(Y[i]>sheet.getRange("C43").getValue(),1,0);
        FQ[i] = IF(Y[i]>sheet.getRange("C44").getValue(),1,0);
        FS[i] = IF(AF[i]>0,Y[i]-Y[i-1],0)+IF(AF[i]==0,AF[i-1],0);
        FT[i] = MAX(sheet.getRange("V2").getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0),0)*(Y[i]-Y[i-1])/ActiveFightDuration;
        FU[i] = IF(AD[i]>0,Y[i]-Y[i-1],0)+IF(AD[i]==0,AD[i-1],0);
        FV[i] = IF(sheet.getRange("FV28").getValue()==0, IF(FV[i-1]-(X[i]-Y[i])>10,FV[i-1]-(X[i]-Y[i])-10,FV[i-1]-(X[i]-Y[i])),0);
        P[i] = IF(Q[i]=="Auto", 1, IF(Q[i]=="Steady", 2,IF(Q[i]=="Multi-Shot", 3,IF(Q[i]=="Raptor", 4, IF(Q[i]=="Melee", 5,IF(Q[i]=="Arcane Shot", 6,IF(Q[i]=="Windfury Attack", 7, 0)))))));
        T[i] = IF(OR(P[i]>0,O[i]==12),IF(FM[i]==1,sheet.getRange("V12").getValue(),0)+IF(AND(EquippedRanged=="Black Bow of the Betrayer",P[i]!=4,P[i]!=5),8,0),0) +IF(Y[i]>5*Math.ceil(Y[i-1]/5),sheet.getRange("V19").getValue(),0) +IF(OR(P[i]==2,P[i]==3),S[i]*IF(EE[i]==1,0.4,0),0)+IF(O[i]==9,EL[i],0)+IF(EM[i]>0,400,0)+IF(O[i]==11.5,EN[i],0);
        U[i] = MIN(U[i-1]-S[i]+T[i],FinalMana);
        V[i] = MAX((sheet.getRange("V2").getValue()-spreadsheet.getSheetByName('Gear').getRange('$Z$24').getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0)-IF(FG[i]>0,sheet.getRange("E39").getValue(),0))-IF(FJ[i]>0,FJ[i]*200,0)-IF(ER[i]==1,300,0)- IF(AL[i]>0, sheet.getRange("V28").getValue(),0),0);
        W[i] = V[i]/(V[i]+400 + 85 * ((5.5 * 70) - 265.5));
        BP[i] = (IF(FQ[i]>0,110,0) + IF(AM[i]>0,sheet.getRange("H29").getValue(),IF(FP[i]>0,sheet.getRange("H43").getValue(),0)) + sheet.getRange("Z19").getValue())*SurvInstinctsAP;
        BR[i] = (IF(AL[i]>0,COUNTIF(sheet.getRange("B15").getValue(),"*Mongoose*")*sheet.getRange("H15").getValue(),0)+IF(AND(AB[i]>0,EquippedTrinket1=="Badge of Tenacity"),150,0)+IF(AND(AC[i]>0,EquippedTrinket2=="Badge of Tenacity"),150,0)+IF(FV[i]<=8.5,GraceofAirAgi,0))*KingsMod*(1+spreadsheet.getSheetByName('Talents').getRange('$E$66').getValue()*0.03);
        BX[i] = MAX(0,sheet.getRange("R7").getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0));
        BY[i] = (sheet.getRange("R6").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-BX[i-1]);
        CE[i] = BY[i]+sheet.getRange("CE29").getValue()*(1-BX[i-1]);
        CJ[i] = BY[i]+sheet.getRange("CJ29").getValue()*(1-BX[i-1]);
        CM[i] = MAX(0,spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$7').getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0))+spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$8').getValue();
        CN[i] = (sheet.getRange("R12").getValue()+sheet.getRange("CN29").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-CM[i-1]);
        CR[i] = sheet.getRange("R12").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100;
        DJ[i] = IF(P[i]==1,1,0);
        DK[i] = IF(P[i]==2,1,0);
        DL[i] = IF(P[i]==3,1,0);
        DM[i] = IF(P[i]==6,1,0);
        DN[i] = IF(P[i]==4,1,0);
        DO[i] = IF(P[i]==5,1,0);
        DP[i] = IF(P[i]==7,1,0);
        DQ[i] = SUM([DJ[i], DK[i], DL[i], DM[i], DN[i], DO[i], DP[i]]);
        EQ[i] = IF(EquippedTrinket1=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0)+IF(EquippedTrinket2=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0);
        ES[i] = MIN(IF(OR(P[i]==1,P[i]==2),33*spreadsheet.getSheetByName('Settings for DPS').getRange('$E$19').getValue(),0)+ES[i-1],330);
        FW[i] = BR[i]*(Y[i]-Y[i-1])/ActiveFightDuration;
        BK[i] = (IF(AA[i]>0,sheet.getRange("H20").getValue(),0)+IF(AB[i]>0,sheet.getRange("H21").getValue(),0)+IF(AC[i]>0,sheet.getRange("H22").getValue(),0)+EI[i]+EQ[i]+IF(AH[i]>0,sheet.getRange("H26").getValue(),0) +IF(AJ[i]>0,sheet.getRange("H14").getValue(),0)+ IF(AK[i]>0,sheet.getRange("H13").getValue(),0)+sheet.getRange("BR32").getValue())*MasterMarksmanAP*SurvInstinctsAP;
        BL[i] = (110+sheet.getRange("Z19").getValue()+ES[i]+IF(AM[i]>0,sheet.getRange("H29").getValue()+BR[i]/4,IF(FP[i]>0,sheet.getRange("H43").getValue(),0)))*MasterMarksmanAP*SurvInstinctsAP;
        BM[i] = BK[i]+BJ[i]+BL[i];
        BO[i] = BK[i]*sheet.getRange("Z11").getValue()/sheet.getRange("Z10").getValue();
        BQ[i] = (BN[i]+BO[i]+BP[i])*IF(FK[i-1]>0,1.1,1);
        CA[i] = (BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*(1-BY[i]-BX[i])+(BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*BY[i]*RangeCritDamage;
        CD[i] = (sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*(1-CE[i]-BX[i])+(sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*CE[i]*RangeCritDamage;
        CH[i] = (spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*(1-BY[i]-BX[i])+(spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*BY[i]*RangeCritDamage;
        CK[i] = (sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*(1-CJ[i]-BX[i])+(sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*CJ[i]*RangeCritDamage;
        CP[i] = (CL[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CN[i])*CO[i]+(CL[i]+BQ[i]*MainhandSpeed/14)*CN[i]*MeleeCritDamage*CO[i];
        CU[i] = (CQ[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*0.25*CT[i]*0.76;
        CV[i] = (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*0.25*CT[i]*0.76;
        FR[i] = (BJ[i]+BK[i])*(Y[i]-Y[i-1])/ActiveFightDuration;
        R[i] = IF(Q[i]=="Arcane Shot",CH[i], IF(O[i]==20,0, IF(Q[i]=="Auto",CA[i],IF(Q[i]=="Steady",CD[i],IF(Q[i]=="Multi-Shot",CK[i],IF(Q[i]=="Raptor",CP[i],IF(Q[i]=="Melee",CU[i],IF(Q[i]=="Windfury Attack",CV[i],0)))))))*(1-W[i]))+IF(Q[i]=="Romulo's Poison Vial",spreadsheet.getSheetByName('Items Calc').getRange('$B$36').getValue()*BZ[i]);
    console.log(O[i],P[i],Q[i],R[i],S[i],T[i],U[i],V[i],W[i],X[i],Y[i],Z[i],AA[i],AB[i],AC[i],AD[i],AE[i],AF[i],AG[i],AH[i],AI[i],AJ[i],AK[i],AL[i],AM[i],AN[i],AO[i],AP[i],AQ[i],AR[i],AS[i],AT[i],AU[i],AV[i],AW[i],AX[i],AY[i],AZ[i],BA[i],BB[i],BC[i],BD[i],BE[i],BF[i],BG[i],BH[i],BI[i],BJ[i],BK[i],BL[i],BM[i],BN[i],BO[i],BP[i],BQ[i],BR[i],BS[i],BT[i],BU[i],BV[i],BW[i],BX[i],BY[i],BZ[i],CA[i],CB[i],CC[i],CD[i],CE[i],CF[i],CG[i],CH[i],CI[i],CJ[i],CK[i],CL[i],CM[i],CN[i],CO[i],CP[i],CQ[i],CR[i],CS[i],CT[i],CU[i],CV[i],CW[i],CX[i],CY[i],CZ[i],DA[i],DB[i],DC[i],DD[i],DE[i],DF[i],DG[i],DH[i],DI[i],DJ[i],DK[i],DL[i],DM[i],DN[i],DO[i],DP[i],DQ[i],DR[i],DS[i],DT[i],DU[i],DV[i],DW[i],DX[i],DY[i],DZ[i],EA[i],EB[i],EC[i],ED[i],EE[i],EF[i],EG[i],EH[i],EI[i],EJ[i],EK[i],EL[i],EM[i],EN[i],EO[i],EP[i],EQ[i],ER[i],ES[i],ET[i],EU[i],EV[i],EW[i],EX[i],EY[i],EZ[i],FA[i],FB[i],FC[i],FD[i],FE[i],FF[i],FG[i],FH[i],FI[i],FJ[i],FK[i],FL[i],FM[i],FN[i],FO[i],FP[i],FQ[i],FR[i],FS[i],FT[i],FU[i],FV[i],FW[i],);
    }
    for (let i = 34; i < 534; i++) {
        AQ[i] = IF(Q[i-1]=="Auto",CB[i-1]-CC[i-1],AQ[i-1]-(Y[i-1]-Y[i-2]));
        AR[i] = IF(Q[i-1]=="Readiness",1,IF(Q[i-1]=="Steady",Z[i-1]-Y[i-1],MAX(AR[i-1]-(Y[i-1]-Y[i-2]),0))+IF(Q[i-1]=="Multi-Shot",Z[i-1]-Y[i-1],0)+IF(Q[i-1]=="Arcane Shot",Z[i-1]-Y[i-1],0));
        AS[i] = IF(Q[i-1]=="Readiness",1,MAX(0,IF(Q[i-1]=="Multi-Shot",sheet.getRange("F7").getValue(),IF(AS[i-1]-(Y[i-1]-Y[i-2])<AR[i],AR[i],MAX(AS[i-1]-(Y[i-1]-Y[i-2]),0)))));
        AT[i] = IF(Q[i-1]==sheet.getRange("B22").getValue(),IF(AT[i-1]>sheet.getRange("O21").getValue(),AT[i-1]-(Y[i-1]-Y[i-2]),sheet.getRange("O21").getValue()), IF(Q[i-1]==sheet.getRange("B21").getValue(),sheet.getRange("F21").getValue(),AT[i-1]-(Y[i-1]-Y[i-2])));
        AU[i] = IF(Q[i-1]==sheet.getRange("B21").getValue(),IF(AU[i-1]>sheet.getRange("O22").getValue(),AU[i-1]-(Y[i-1]-Y[i-2]),sheet.getRange("O22").getValue()),IF(Q[i-1]==sheet.getRange("B22").getValue(),sheet.getRange("F22").getValue(),AU[i-1]-(Y[i-1]-Y[i-2])));
        AV[i] = IF(OR(Q[i-1]=="Blood Fury", Q[i-1]=="Berserking"),VLOOKUP(O[i-1],CLReferenceTable,6,false),AV[i-1]-(Y[i-1]-Y[i-2]));
        AW[i] = IF(Q[i-1]=="The Beast Within",sheet.getRange("F19").getValue(),AW[i-1]-(Y[i-1]-Y[i-2]));
        AX[i] = IF(Q[i-1]=="Readiness",0,IF(Q[i-1]=="Raptor",sheet.getRange("F9").getValue(),IF(Q[i-1]=="Melee",IF(AX[i-1]<=CS[i-1],CS[i-1],AX[i-1]-(Y[i-1]-Y[i-2])),AX[i-1]-(Y[i-1]-Y[i-2]))));
        AY[i] = IF(Q[i-1]=="Melee",CS[i-1],IF(Q[i-1]=="Raptor",CS[i-1],AY[i-1]-(Y[i-1]-Y[i-2])));
        AZ[i] = IF(Q[i-1]=="Readiness",1,MAX(0,IF(Q[i-1]=="Arcane Shot",sheet.getRange("F6").getValue(),IF(AZ[i-1]-(Y[i-1]-Y[i-2])<AR[i],AR[i],MAX(AZ[i-1]-(Y[i-1]-Y[i-2]),0)))));
        BA[i] = IF(Q[i-1]=="Readiness",VLOOKUP(O[i-1],CLReferenceTable,6,false), MAX(IF( AO[i-1]>0,AO[i-1],0),BA[i-1]-(Y[i-1]-Y[i-2])));
        BB[i] = IF(Q[i-1]=="Band of the Eternal Champion",60,BB[i-1]-(Y[i-1]-Y[i-2]));
        BC[i] = MAX(0,IF(Q[i-1]=="Quick Shots",CB[i-1],BC[i-1]-(Y[i-1]-Y[i-2])));
        BD[i] = IF(Q[i-1]=="Blood Lust",IF(AND(sheet.getRange("BE19").getValue()!=0,OR(EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-1,EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-2,EJ[i-1]==spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$C$26').getValue()-3)),sheet.getRange("BE19").getValue(),sheet.getRange("BE18").getValue()),BD[i-1]-(Y[i-1]-Y[i-2]));
        BE[i] = IF(O[i-1]==9,120,BE[i-1]-(Y[i-1]-Y[i-2]));
        BF[i] = IF(O[i-1]==11.5,120,BF[i-1]-(Y[i-1]-Y[i-2]));
        BG[i] = IF(Q[i-1]=="Drums",sheet.getRange("F26").getValue(),BG[i-1]-(Y[i-1]-Y[i-2]));
        BH[i] = IF(Q[i-1]=="Readiness",0,IF(O[i-1]==12,5,BH[i-1]-(Y[i-1]-Y[i-2])));
        BI[i] = IF(Q[i-1]=="Readiness",0,IF(Q[i-1]=="Rapid",VLOOKUP(O[i-1],CLReferenceTable,6,false),BI[i-1]-(Y[i-1]-Y[i-2])));
        BJ[i] = sheet.getRange("R2").getValue();
        BN[i] = sheet.getRange("R1").getValue();
        BS[i] = sheet.getRange("R11").getValue();
        BT[i] = sheet.getRange("R10").getValue()+IF(AC[i-1]>0,sheet.getRange("J22").getValue(),0)+IF(AB[i-1]>0,sheet.getRange("J21").getValue(),0)+IF(AG[i-1]>0,sheet.getRange("J25").getValue(),0)+IF(AH[i-1]>0,sheet.getRange("J26").getValue(),0);
        BU[i] = IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*IF(AF[i-1]>0,1.3,1)*IF(AA[i-1]>0,1+sheet.getRange("I20").getValue(),1);
        BV[i] = BS[i]*BU[i]*(1+BT[i]/HasteRatingRatio/100);
        BW[i] = sheet.getRange("R4").getValue();
        CB[i] = RangedWeaponSpeed/BV[i];
        CC[i] = 0.5/BV[i];
        CF[i] = 1.5/BV[i];
        CL[i] = sheet.getRange("CL31").getValue();
        CQ[i] = sheet.getRange("CQ31").getValue();
        CS[i] = sheet.getRange("CS29").getValue()/BV[i]*IF(AO[i-1]>0,1.4,1)*IF(AE[i-1]>0,1.15,1)*BS[i];
        CX[i] = CD[i-1]/((MAX(AR[i],0)*(CB[i-1]*sheet.getRange("CX31").getValue())+CF[i-1]));
        CY[i] = CA[i-1]/(MAX(AQ[i],0)*CB[i-1]*sheet.getRange("CY31").getValue()+CC[i-1]);
        DB[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$11').getValue()==true, CP[i-1]/(MAX(AX[i],0)+sheet.getRange("D9").getValue())/(CB[i-1]*sheet.getRange("DB31").getValue()),0);
        DC[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$12').getValue()==true, CU[i-1]/(MAX(AY[i],0)+sheet.getRange("D11").getValue())/(CB[i-1]*sheet.getRange("DC31").getValue()),0);
        DF[i] = IF(O[i-1]<12,DF[i-1],IF(CW[i-1]=="Steady", IF(AND(AP[i-2]!=20, CW[i-1]=="Steady"),IF(AND(AP[i-2]!=20,AP[i-1]!=20),0,1),IF(AND(CW[i-2]=="Auto",AP[i-1]==20), IF(DG[i-1]<0.4,1,0),0)),IF(AND(O[i-1]<13, OR(CW[i-1]=="Arcane Shot",CW[i-1]=="Multi-Shot")),1, IF(CW[i-1]=="Auto",IF(CW[i-2]=="Arcane Shot",IF(CB[i-1]-CC[i-1]-DG[i-1]>0.4,0,0),0),0))));
        DG[i] = MAX(Z[i-1]-Y[i-1],0);
        DR[i] = IF(P[i-1]>0,1,0)+DR[i-1];
        DS[i] = DR[i];
        DT[i] = IF(sheet.getRange("Z6").getValue()==2,DQ[i-1],IF(sheet.getRange("Z6").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z6").getValue()==3,DK[i-1],0)));
        DU[i] = IF(sheet.getRange("Z7").getValue()==2,DQ[i-1],IF(sheet.getRange("Z7").getValue()==1,IF(O[i-1]>12,DI[i-1],0),IF(sheet.getRange("Z7").getValue()==3,DK[i-1],0)));
        DV[i] = MAX(0,IF(AT[i]>0,0,MIN(DT[i]*sheet.getRange("Z4").getValue()+DV[i-1],1)-IF(Q[i-1]==EquippedTrinket1,1,0)));
        DW[i] = MAX(0,IF(AU[i]>0,0,MIN(DU[i]*sheet.getRange("Z5").getValue()+DW[i-1],1)-IF(Q[i-1]==EquippedTrinket2,1,0)));
        DX[i] = MIN(DJ[i-1]*sheet.getRange("Z3").getValue()+DX[i-1],1)-IF(Q[i-1]=="Quick Shots",1,0);
        DY[i] = MIN(DQ[i-1]*sheet.getRange("Z8").getValue()+DY[i-1],1)-IF(Q[i-1]=="Master Tactician",1,0);
        EA[i] = IF(OR(EquippedRing1=="Band of the Eternal Champion", EquippedRing2=="Band of the Eternal Champion"), IF(BB[i]>0,0,MIN(DQ[i-1]*sheet.getRange("Z13").getValue()+EA[i-1],1)-IF(Q[i-1]=="Band of the Eternal Champion",1,0)),0);
        EB[i] = IF(EquippedRanged!="Don Santos' Famous Hunting Rifle",0,MIN((DJ[i-1]+DK[i-1]+DL[i-1]+DM[i-1])*sheet.getRange("Z14").getValue()+EB[i-1],1)-IF(Q[i-1]=="Santos' Blessing",1,0));
        EC[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z15").getValue()+EC[i-1],1)-IF(Q[i-1]==EnchantMainhand,1,0);
        ED[i] = MIN((DN[i-1]+DO[i-1])*sheet.getRange("Z16").getValue()+ED[i-1],1)-IF(Q[i-1]=="Windfury Attack",1,0);
        EE[i] = MIN(DK[i-1]*sheet.getRange("Z12").getValue()+EE[i-1],1)-IF(EE[i-1]==1,1,0);
        EH[i] = IF(DI[i-1]==1,5-(Y[i-1]-Y[i-2]), IF(EH[i-1]-(Y[i-1]-Y[i-2])>0,EH[i-1]-(Y[i-1]-Y[i-2]),0));
        EK[i] = IF(IF(O[i-1]==20,0,Math.floor(VLOOKUP(CW[i-1],sheet.getRange('$B$3:$N$29').getValues(),4,false)*IF(AD[i-2]>0,0.8,1),0))>U[i-2],18,0);
        DD[i] = IF( DF[i]==1,sheet.getRange("DD31").getValue()*IF(MAX(AQ[i],0)<0.2,2,1),IF(CW[i-1]=="Auto",IF(CB[i-1]<1.8,CB[i-1]*1.2,CB[i-1]*2.3),20));
        DE[i] = IF(DF[i]==1,IF(CW[i-1]!="Multi-Shot",sheet.getRange("DE31").getValue(),200),200);
        DH[i] = IF(DQ[i-1]==0,DH[i-1], IF(DS[i]>DS[i-1],sheet.getRange("DH29").getValue(),0)+DH[i-1]-DI[i-1]);
        DI[i] = IF(DH[i]>1,1,0);
        DZ[i] = MIN(DI[i]*sheet.getRange("Z9").getValue()+DZ[i-1],1)-IF(Q[i-1]=="Expose Weakness",1,0);
        EG[i] = IF(sheet.getRange("EG28").getValue()==true, IF(BH[i]<=0,IF(EH[i]>0,1,0),0),0);
        AP[i] = IF(DV[i]==1,3,IF(DW[i]==1,6,IF(DX[i]==1,5,IF(DY[i]==1,7,IF(DZ[i]==1,11,IF(AND(EG[i]==1,75<=U[i-1]),12,IF(EA[i]==1,11.2,IF(EB[i]==1,11.1,IF(EC[i]==1,11.3,IF(ED[i]==1,11.4,20))))))))));
        CZ[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$9').getValue()==true, CK[i-1]/(MAX(AS[i],0)+CC[i-1])/(DD[i]),0);
        DA[i] = IF(spreadsheet.getSheetByName('Settings for DPS').getRange('$F$10').getValue()==true, (CH[i-1]*(1+W[i-1]))/(MAX(AZ[i],0)+0.01)/(DE[i]),0);
        CW[i] = IF(CX[i]+CY[i]+CZ[i]+DB[i]+DC[i]==0,"None",IF(S[i-1]>=U[i-1], "Auto",INDEX(sheet.getRange('$CX$30:$DC$30').getValues(),0, MATCH(MAX([CX[i], CY[i], CZ[i], DA[i], DB[i], DC[i]]),[CX[i], CY[i], CZ[i], DA[i], DB[i], DC[i]],0))));
        O[i] = IF(AND(EK[i]==18,AP[i]==20),18, MIN(IF(AW[i]<=0,1,20),IF(AV[i]<=0,2,20),IF(sheet.getRange("K21").getValue()=="Yes",AP[i], IF(AT[i]<=0,3,20)),IF(sheet.getRange("K22").getValue()=="Yes",AP[i], IF(AU[i]<=0,6,20)),IF(BI[i]<=0,4,20), IF(CW[i]=="Auto",18,IF(CW[i]=="Steady",19,IF(CW[i]=="Multi-Shot",14,IF(CW[i]=="Raptor",13,IF(CW[i]=="Melee",15,IF(CW[i]=="Arcane Shot",17,20)))))),AP[i],IF(BD[i]<=0,8,20),IF(BE[i]<=0,9,20),IF(BF[i]<=0,11.5,20),IF(BA[i]<=0,11.6,20),IF(BG[i]<=0,10,20)));
        Q[i] = VLOOKUP(O[i],CLReferenceTable,2,false);
        S[i] = IF(O[i]==20,0,Math.floor(VLOOKUP(O[i],CLReferenceTable,5,false)*IF(AD[i-1]>0,0.8,1),0));
        X[i] = Y[i-1]+IF(Q[i]=="Auto",MAX(AQ[i],0),IF(Q[i]=="Steady",MAX(AR[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Multi-Shot", MAX(AS[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Raptor",MAX(AX[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Melee",MAX(AY[i],0)+sheet.getRange("AG22").getValue(),IF(Q[i]=="Arcane Shot",MAX(AZ[i],0)+sheet.getRange("AG22").getValue(),0))))));
        Y[i] = X[i]+IF(Q[i]=="Auto",CC[i], IF(Q[i]=="Steady",CF[i],IF(Q[i]=="Multi-Shot",CC[i],IF(Q[i]=="Raptor",sheet.getRange("D9").getValue(),IF(Q[i]=="Melee",sheet.getRange("D11").getValue(),IF(Q[i]=="Arcane Shot", sheet.getRange("D6").getValue(), IF(Q[i]=="None",MIN(MAX(AQ[i],0),MAX(AR[i],0),MAX(AS[i],0),0),0)))))));
        Z[i] = IF(VLOOKUP(O[i],CLReferenceTable,14,false)=="YES",X[i]+1.5,IF(X[i]<Z[i-1],Z[i-1],0));
        AA[i] = MAX(0,IF(OR(Q[i]=="Blood Fury", Q[i]=="Berserking"),VLOOKUP(O[i],CLReferenceTable,7,false),AA[i-1]-(Y[i]-Y[i-1])));
        AB[i] = MAX(0,IF(Q[i]==sheet.getRange("B21").getValue(),sheet.getRange("G21").getValue(),AB[i-1]-(Y[i]-Y[i-1])));
        AC[i] = MAX(0,IF(Q[i]==sheet.getRange("B22").getValue(),sheet.getRange("G22").getValue(),AC[i-1]-(Y[i]-Y[i-1])));
        AD[i] = MAX(0,IF(Q[i]=="The Beast Within",18,AD[i-1]-(Y[i]-Y[i-1])));
        AE[i] = MAX(0,IF(Q[i]=="Quick Shots",12,AE[i-1]-(Y[i]-Y[i-1])));
        AF[i] = MAX(0,IF(Q[i]=="Blood Lust",40,AF[i-1]-(Y[i]-Y[i-1])));
        AG[i] = MAX(0,IF(Q[i]=="Haste Potion",15,IF(Q[i]=="Fel Mana Potion",24,AG[i-1]-(Y[i]-Y[i-1]))));
        AH[i] = MAX(0,IF(Q[i]=="Drums",sheet.getRange("G26").getValue(),AH[i-1]-(Y[i]-Y[i-1])));
        AI[i] = MAX(0,IF(Q[i]=="Master Tactician",8,AI[i-1]-(Y[i]-Y[i-1])));
        AJ[i] = MAX(0,IF(Q[i]=="Band of the Eternal Champion",10,AJ[i-1]-(Y[i]-Y[i-1])));
        AK[i] = MAX(0,IF(Q[i]=="Santos' Blessing",10,AK[i-1]-(Y[i]-Y[i-1])));
        AL[i] = MAX(0,IF(Q[i]==EnchantMainhand,15,AL[i-1]-(Y[i]-Y[i-1])));
        AM[i] = MAX(0,IF(Q[i]=="Expose Weakness",7,AM[i-1]-(Y[i]-Y[i-1])));
        AN[i] = IF(SetBeastLord>=4,IF(MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1])))>0,MAX(0,IF(EG[i]==1,15,AN[i-1]-(Y[i]-Y[i-1]))),0),0);
        AO[i] = MAX(0,IF(Q[i]=="Rapid",sheet.getRange("G8").getValue(),AO[i-1]-(Y[i]-Y[i-1])));
        BZ[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CG[i] = sheet.getRange("R9").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FN[i-1]>0,sheet.getRange("I41").getValue(),1)*IF(FO[i-1]>0,sheet.getRange("I42").getValue(),1);
        CI[i] = BZ[i]*BarrageMod*PvPGloveMod;
        CO[i] = sheet.getRange("R15").getValue()*(IF(AD[i]>0,1.1,1))*IF(FH[i-1]>0,sheet.getRange("I35").getValue(),1)*IF(FI[i-1]>0,1.04,1);
        CT[i] = CO[i];
        EF[i] = IF(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),DT[i]*sheet.getRange("Z4").getValue()+EF[i-1],IF(AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0),DU[i]*sheet.getRange("Z5").getValue()+EF[i-1],0))-IF(ET[i-1]==1,1,0);
        EI[i] = IF(EquippedTrinket1=="Blackened Naaru Sliver", MIN(IF(AB[i]>0,44*DT[i]+EI[i-1],0),440),0)+IF(EquippedTrinket2=="Blackened Naaru Sliver", MIN(IF(AC[i]>0,44*DU[i]+EI[i-1],0),440),0);
        EJ[i] = IF(O[i]==8,1+EJ[i-1],EJ[i-1]);
        EL[i] = IF(sheet.getRange("B25").getValue()=="Super Mana Potion",IF(O[i]==9,spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$K$20').getValue(),0),0);
        EM[i] = IF((IF(sheet.getRange("B25").getValue()=="Fel Mana Potion",Math.ceil(AG[i]/3)-Math.ceil(AG[i-1]/3),0)+EM[i-1])!=EM[i-1],IF(O[i]==9,0,1),0);
        EN[i] = IF(AND(O[i]==11.5,COUNTIF(spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$I$21').getValue(),"*Rune")==1),1200,0);
        EO[i] = IF(Y[i]-Y[i-1]==0,0,IF(AQ[i]<0,Math.abs(AQ[i]),0));
        ER[i] = IF(OR(AND(EquippedTrinket1=="Madness of the Betrayer",AB[i]>0),AND(EquippedTrinket2=="Madness of the Betrayer",AC[i]>0)),1,0);
        ET[i] = IF(EF[i]>=1,1,0);
        EU[i] = IF(AB[i]>0,Y[i]-Y[i-1],0)+IF(AB[i]==0,AB[i-1],0);
        EV[i] = IF(AC[i]>0,Y[i]-Y[i-1],0)+IF(AC[i]==0,AC[i-1],0);
        EW[i] = IF(AE[i]>0,Y[i]-Y[i-1],0)+IF(AE[i]==0,AE[i-1],0);
        EX[i] = IF(AI[i]>0,Y[i]-Y[i-1],0)+IF(AI[i]==0,AI[i-1],0);
        EY[i] = IF(AM[i]>0,Y[i]-Y[i-1],0)+IF(AM[i]==0,AM[i-1],0);
        EZ[i] = IF(AJ[i]>0,Y[i]-Y[i-1],0)+IF(AJ[i]==0,AJ[i-1],0);
        FA[i] = IF(AK[i]>0,Y[i]-Y[i-1],0)+IF(AK[i]==0,AK[i-1],0);
        FB[i] = IF(AL[i]>0,Y[i]-Y[i-1],0)+IF(AL[i]==0,AL[i-1],0);
        FC[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),0,IF(Y[i]>=sheet.getRange("C31").getValue(),1,0));
        FD[i] = IF(Y[i]>=sheet.getRange("C32").getValue(),1,0);
        FE[i] = IF(Y[i]>=sheet.getRange("C33").getValue(),1,0);
        FF[i] = IF(Y[i]>=sheet.getRange("C34").getValue(),1,0);
        FG[i] = IF(AN[i]>0,1,0);
        FH[i] = IF(Y[i]>sheet.getRange("C35").getValue(),1,0);
        FI[i] = IF(Y[i]>sheet.getRange("C36").getValue(),1,0);
        FJ[i] = IF(OR(AND(EquippedTrinket1=="Badge of the Swarmguard",AB[i]>0),AND(EquippedTrinket2=="Badge of the Swarmguard",AC[i]>0)),MIN(6,IF(ET[i]==1,ET[i]+FJ[i-1],FJ[i-1])),0);
        FK[i] = IF(Y[i]>sheet.getRange("C38").getValue(),1,0);
        FL[i] = IF(Y[i]>sheet.getRange("C37").getValue(),1,0);
        FM[i] = IF(Y[i]>sheet.getRange("C40").getValue(),1,0);
        FN[i] = IF(Y[i]>sheet.getRange("C41").getValue(),1,0);
        FO[i] = IF(Y[i]>sheet.getRange("C42").getValue(),1,0);
        FP[i] = IF(Y[i]>sheet.getRange("C43").getValue(),1,0);
        FQ[i] = IF(Y[i]>sheet.getRange("C44").getValue(),1,0);
        FS[i] = IF(AF[i]>0,Y[i]-Y[i-1],0)+IF(AF[i]==0,AF[i-1],0);
        FT[i] = MAX(sheet.getRange("V2").getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0),0)*(Y[i]-Y[i-1])/ActiveFightDuration;
        FU[i] = IF(AD[i]>0,Y[i]-Y[i-1],0)+IF(AD[i]==0,AD[i-1],0);
        FV[i] = IF(sheet.getRange("FV28").getValue()==0, IF(FV[i-1]-(X[i]-Y[i])>10,FV[i-1]-(X[i]-Y[i])-10,FV[i-1]-(X[i]-Y[i])),0);
        P[i] = IF(Q[i]=="Auto", 1, IF(Q[i]=="Steady", 2,IF(Q[i]=="Multi-Shot", 3,IF(Q[i]=="Raptor", 4, IF(Q[i]=="Melee", 5,IF(Q[i]=="Arcane Shot", 6,IF(Q[i]=="Windfury Attack", 7, 0)))))));
        T[i] = IF(OR(P[i]>0,O[i]==12),IF(FM[i]==1,sheet.getRange("V12").getValue(),0)+IF(AND(EquippedRanged=="Black Bow of the Betrayer",P[i]!=4,P[i]!=5),8,0),0) +IF(Y[i]>5*Math.ceil(Y[i-1]/5),sheet.getRange("V19").getValue(),0) +IF(OR(P[i]==2,P[i]==3),S[i]*IF(EE[i]==1,0.4,0),0)+IF(O[i]==9,EL[i],0)+IF(EM[i]>0,400,0)+IF(O[i]==11.5,EN[i],0);
        U[i] = MIN(U[i-1]-S[i]+T[i],FinalMana);
        V[i] = MAX((sheet.getRange("V2").getValue()-spreadsheet.getSheetByName('Gear').getRange('$Z$24').getValue()-IF(FC[i]>0,sheet.getRange("E31").getValue(),0)-IF(FD[i]>0,sheet.getRange("E32").getValue(),0)-IF(FE[i]>0,sheet.getRange("E33").getValue(),0)-IF(FF[i]>0,sheet.getRange("E34").getValue(),0)-IF(FG[i]>0,sheet.getRange("E39").getValue(),0))-IF(FJ[i]>0,FJ[i]*200,0)-IF(ER[i]==1,300,0)- IF(AL[i]>0, sheet.getRange("V28").getValue(),0),0);
        W[i] = V[i]/(V[i]+400 + 85 * ((5.5 * 70) - 265.5));
        BP[i] = (IF(FQ[i]>0,110,0) + IF(AM[i]>0,sheet.getRange("H29").getValue(),IF(FP[i]>0,sheet.getRange("H43").getValue(),0)) + sheet.getRange("Z19").getValue())*SurvInstinctsAP;
        BR[i] = (IF(AL[i]>0,COUNTIF(sheet.getRange("B15").getValue(),"*Mongoose*")*sheet.getRange("H15").getValue(),0)+IF(AND(AB[i]>0,EquippedTrinket1=="Badge of Tenacity"),150,0)+IF(AND(AC[i]>0,EquippedTrinket2=="Badge of Tenacity"),150,0)+IF(FV[i]<=8.5,GraceofAirAgi,0))*KingsMod*(1+spreadsheet.getSheetByName('Talents').getRange('$E$66').getValue()*0.03);
        BX[i] = MAX(0,sheet.getRange("R7").getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0));
        BY[i] = (sheet.getRange("R6").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-BX[i-1]);
        CE[i] = BY[i]+sheet.getRange("CE29").getValue()*(1-BX[i-1]);
        CJ[i] = BY[i]+sheet.getRange("CJ29").getValue()*(1-BX[i-1]);
        CM[i] = MAX(0,spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$7').getValue() - IF(FF[i]==1,sheet.getRange("J34").getValue(),0))+spreadsheet.getSheetByName('Player DPS Calc').getRange('$F$8').getValue();
        CN[i] = (sheet.getRange("R12").getValue()+sheet.getRange("CN29").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100)*(1-CM[i-1]);
        CR[i] = sheet.getRange("R12").getValue()+IF(AI[i-1]>0,sheet.getRange("AA8").getValue(),0)+IF(FL[i-1]>0,0.03,0)+BR[i]/AgilityToCrit/100;
        DJ[i] = IF(P[i]==1,1,0);
        DK[i] = IF(P[i]==2,1,0);
        DL[i] = IF(P[i]==3,1,0);
        DM[i] = IF(P[i]==6,1,0);
        DN[i] = IF(P[i]==4,1,0);
        DO[i] = IF(P[i]==5,1,0);
        DP[i] = IF(P[i]==7,1,0);
        DQ[i] = SUM([DJ[i], DK[i], DL[i], DM[i], DN[i], DO[i], DP[i]]);
        EQ[i] = IF(EquippedTrinket1=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0)+IF(EquippedTrinket2=="Darkmoon Card: Crusade", MIN(IF(P[i]>0,6*DS[i],EQ[i-1]),120),0);
        ES[i] = MIN(IF(OR(P[i]==1,P[i]==2),33*spreadsheet.getSheetByName('Settings for DPS').getRange('$E$19').getValue(),0)+ES[i-1],330);
        FW[i] = BR[i]*(Y[i]-Y[i-1])/ActiveFightDuration;
        BK[i] = (IF(AA[i]>0,sheet.getRange("H20").getValue(),0)+IF(AB[i]>0,sheet.getRange("H21").getValue(),0)+IF(AC[i]>0,sheet.getRange("H22").getValue(),0)+EI[i]+EQ[i]+IF(AH[i]>0,sheet.getRange("H26").getValue(),0) +IF(AJ[i]>0,sheet.getRange("H14").getValue(),0)+ IF(AK[i]>0,sheet.getRange("H13").getValue(),0)+sheet.getRange("BR32").getValue())*MasterMarksmanAP*SurvInstinctsAP;
        BL[i] = (110+sheet.getRange("Z19").getValue()+ES[i]+IF(AM[i]>0,sheet.getRange("H29").getValue()+BR[i]/4,IF(FP[i]>0,sheet.getRange("H43").getValue(),0)))*MasterMarksmanAP*SurvInstinctsAP;
        BM[i] = BK[i]+BJ[i]+BL[i];
        BO[i] = BK[i]*sheet.getRange("Z11").getValue()/sheet.getRange("Z10").getValue();
        BQ[i] = (BN[i]+BO[i]+BP[i])*IF(FK[i-1]>0,1.1,1);
        CA[i] = (BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*(1-BY[i]-BX[i])+(BW[i]+BM[i]*RangedWeaponSpeed/14)*BZ[i]*BY[i]*RangeCritDamage;
        CD[i] = (sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*(1-CE[i]-BX[i])+(sheet.getRange("R5").getValue()+BM[i]*0.2)*BZ[i]*GronnStalkerSSMod*CE[i]*RangeCritDamage;
        CH[i] = (spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*(1-BY[i]-BX[i])+(spreadsheet.getSheetByName('Player DPS Calc').getRange('$C$36').getValue()+BM[i]*0.15)*CG[i]*BY[i]*RangeCritDamage;
        CK[i] = (sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*(1-CJ[i]-BX[i])+(sheet.getRange("CI28").getValue()+BM[i]*0.2)*CI[i]*CJ[i]*RangeCritDamage;
        CP[i] = (CL[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CN[i])*CO[i]+(CL[i]+BQ[i]*MainhandSpeed/14)*CN[i]*MeleeCritDamage*CO[i];
        CU[i] = (CQ[i]+BQ[i]*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+(CQ[i]+BQ[i]*MainhandSpeed/14)*0.25*CT[i]*0.76;
        CV[i] = (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*(1-CM[i]-CR[i]-0.25)*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*CR[i]*MeleeCritDamage*CT[i]+ (CQ[i]+(BQ[i]+spreadsheet.getSheetByName('Buffs and Debuffs').getRange('$G$23').getValue())*MainhandSpeed/14)*0.25*CT[i]*0.76;
        FR[i] = (BJ[i]+BK[i])*(Y[i]-Y[i-1])/ActiveFightDuration;
        R[i] = IF(Q[i]=="Arcane Shot",CH[i], IF(O[i]==20,0, IF(Q[i]=="Auto",CA[i],IF(Q[i]=="Steady",CD[i],IF(Q[i]=="Multi-Shot",CK[i],IF(Q[i]=="Raptor",CP[i],IF(Q[i]=="Melee",CU[i],IF(Q[i]=="Windfury Attack",CV[i],0)))))))*(1-W[i]))+IF(Q[i]=="Romulo's Poison Vial",spreadsheet.getSheetByName('Items Calc').getRange('$B$36').getValue()*BZ[i]);
    console.log(O[i],P[i],Q[i],R[i],S[i],T[i],U[i],V[i],W[i],X[i],Y[i],Z[i],AA[i],AB[i],AC[i],AD[i],AE[i],AF[i],AG[i],AH[i],AI[i],AJ[i],AK[i],AL[i],AM[i],AN[i],AO[i],AP[i],AQ[i],AR[i],AS[i],AT[i],AU[i],AV[i],AW[i],AX[i],AY[i],AZ[i],BA[i],BB[i],BC[i],BD[i],BE[i],BF[i],BG[i],BH[i],BI[i],BJ[i],BK[i],BL[i],BM[i],BN[i],BO[i],BP[i],BQ[i],BR[i],BS[i],BT[i],BU[i],BV[i],BW[i],BX[i],BY[i],BZ[i],CA[i],CB[i],CC[i],CD[i],CE[i],CF[i],CG[i],CH[i],CI[i],CJ[i],CK[i],CL[i],CM[i],CN[i],CO[i],CP[i],CQ[i],CR[i],CS[i],CT[i],CU[i],CV[i],CW[i],CX[i],CY[i],CZ[i],DA[i],DB[i],DC[i],DD[i],DE[i],DF[i],DG[i],DH[i],DI[i],DJ[i],DK[i],DL[i],DM[i],DN[i],DO[i],DP[i],DQ[i],DR[i],DS[i],DT[i],DU[i],DV[i],DW[i],DX[i],DY[i],DZ[i],EA[i],EB[i],EC[i],ED[i],EE[i],EF[i],EG[i],EH[i],EI[i],EJ[i],EK[i],EL[i],EM[i],EN[i],EO[i],EP[i],EQ[i],ER[i],ES[i],ET[i],EU[i],EV[i],EW[i],EX[i],EY[i],EZ[i],FA[i],FB[i],FC[i],FD[i],FE[i],FF[i],FG[i],FH[i],FI[i],FJ[i],FK[i],FL[i],FM[i],FN[i],FO[i],FP[i],FQ[i],FR[i],FS[i],FT[i],FU[i],FV[i],FW[i],);
    }
}